// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "74b9c954"
 *  Spreadsheet Format Version - '25'
 **/

#include "data_structures/td_control_structures.h"

tdx_static_assert(offsetof(tdr_t, management_fields.fatal) == 0x0000, fatal);
tdx_static_assert(offsetof(tdr_t, management_fields.num_tdcx) == 0x0004, num_tdcx);
tdx_static_assert(offsetof(tdr_t, management_fields.chldcnt) == 0x0008, chldcnt);
tdx_static_assert(offsetof(tdr_t, management_fields.lifecycle_state) == 0x0010, lifecycle_state);
tdx_static_assert(offsetof(tdr_t, management_fields.tdcx_pa) == 0x0018, tdcx_pa);
tdx_static_assert(offsetof(tdr_t, management_fields.td_uuid) == 0x0080, td_uuid);
tdx_static_assert(offsetof(tdr_t, key_management_fields.hkid) == 0x0100, hkid);
tdx_static_assert(offsetof(tdr_t, key_management_fields.pkg_config_bitmap) == 0x0108, pkg_config_bitmap);
tdx_static_assert(offsetof(tdr_t, td_preserving_fields.handoff_version) == 0x0140, handoff_version);
tdx_static_assert(offsetof(tdr_t, td_preserving_fields.seamdb_index) == 0x0148, seamdb_index);
tdx_static_assert(offsetof(tdr_t, td_preserving_fields.seamdb_nonce) == 0x0150, seamdb_nonce);
tdx_static_assert(offsetof(tdr_t, tdx_io_fields.rnd_hpa_offset_6b) == 0x0180, rnd_hpa_offset_6b);
tdx_static_assert(offsetof(tdr_t, tdx_io_fields.devif_ref_cnt) == 0x0188, devif_ref_cnt);
tdx_static_assert(offsetof(tdcs_t, management_fields.num_vcpus) == 0x0000, num_vcpus);
tdx_static_assert(offsetof(tdcs_t, management_fields.num_assoc_vcpus) == 0x0004, num_assoc_vcpus);
tdx_static_assert(offsetof(tdcs_t, management_fields.op_state) == 0x0008, op_state);
tdx_static_assert(offsetof(tdcs_t, management_fields.num_l2_vms) == 0x0010, num_l2_vms);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.attributes) == 0x0080, attributes);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.xfam) == 0x0088, xfam);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.max_vcpus) == 0x0090, max_vcpus);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.gpaw) == 0x0094, gpaw);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.eptp) == 0x0098, eptp);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.tsc_offset) == 0x00A8, tsc_offset);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.tsc_multiplier) == 0x00B0, tsc_multiplier);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.tsc_frequency) == 0x00B8, tsc_frequency);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.xbuff_size) == 0x00DC, xbuff_size);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.notify_enables) == 0x00E0, notify_enables);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.hp_lock_timeout) == 0x00E8, hp_lock_timeout);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.vm_ctls) == 0x00F0, vm_ctls);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.config_flags) == 0x0118, config_flags);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.td_ctls) == 0x0120, td_ctls);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.virt_maxpa) == 0x0128, virt_maxpa);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.topology_enum_configured) == 0x012C, topology_enum_configured);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.ve_reduction_valid) == 0x012D, ve_reduction_valid);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.cpuid_fixed0_bitmap) == 0x1488, cpuid_fixed0_bitmap);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.feature_paravirt_ctls) == 0x14D8, feature_paravirt_ctls);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.filtered_events_count) == 0x14E0, filtered_events_count);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.event_filters_num) == 0x1500, event_filters_num);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.cpuid_valid) == 0x0134, cpuid_valid);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.cpuid4_native_values) == 0x1490, cpuid4_native_values);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.cpuid4_native_valid) == 0x14D0, cpuid4_native_valid);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.xbuff_offsets) == 0x01E0, xbuff_offsets);
tdx_static_assert(offsetof(tdcs_t, epoch_tracking.epoch_and_refcount.td_epoch) == 0x0280, td_epoch);
tdx_static_assert(offsetof(tdcs_t, epoch_tracking.epoch_and_refcount.refcount) == 0x0288, refcount);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrtd) == 0x02C0, mrtd);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrconfigid) == 0x02F0, mrconfigid);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrowner) == 0x0320, mrowner);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrownerconfig) == 0x0350, mrownerconfig);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.rtmr) == 0x0380, rtmr);
tdx_static_assert(offsetof(tdcs_t, cpuid_values) == 0x0880, cpuid_values);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_arch_capabilities) == 0x07F8, virtual_ia32_arch_capabilities);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_basic) == 0x0780, virtual_ia32_vmx_basic);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_misc) == 0x0788, virtual_ia32_vmx_misc);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr0_fixed0) == 0x0790, virtual_ia32_vmx_cr0_fixed0);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr0_fixed1) == 0x0798, virtual_ia32_vmx_cr0_fixed1);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr4_fixed0) == 0x07A0, virtual_ia32_vmx_cr4_fixed0);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr4_fixed1) == 0x07A8, virtual_ia32_vmx_cr4_fixed1);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_procbased_ctls2) == 0x07B0, virtual_ia32_vmx_procbased_ctls2);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_ept_vpid_cap) == 0x07B8, virtual_ia32_vmx_ept_vpid_cap);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_pinbased_ctls) == 0x07C0, virtual_ia32_vmx_true_pinbased_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_procbased_ctls) == 0x07C8, virtual_ia32_vmx_true_procbased_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_exit_ctls) == 0x07D0, virtual_ia32_vmx_true_exit_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_entry_ctls) == 0x07D8, virtual_ia32_vmx_true_entry_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_vmfunc) == 0x07E0, virtual_ia32_vmx_vmfunc);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_procbased_ctls3) == 0x07E8, virtual_ia32_vmx_procbased_ctls3);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_exit_ctls2) == 0x07F0, virtual_ia32_vmx_exit_ctls2);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_dec_key_set) == 0x0600, mig_dec_key_set);
tdx_static_assert(offsetof(tdcs_t, migration_fields.export_count) == 0x0604, export_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.import_count) == 0x0608, import_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_epoch) == 0x060C, mig_epoch);
tdx_static_assert(offsetof(tdcs_t, migration_fields.bw_epoch) == 0x0610, bw_epoch);
tdx_static_assert(offsetof(tdcs_t, migration_fields.total_mb_count) == 0x0618, total_mb_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_dec_key) == 0x0620, mig_dec_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_dec_working_key) == 0x0640, mig_dec_working_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_enc_key) == 0x0660, mig_enc_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_enc_working_key) == 0x0680, mig_enc_working_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_version) == 0x06A0, mig_version);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_working_version) == 0x06A2, mig_working_version);
tdx_static_assert(offsetof(tdcs_t, migration_fields.dirty_count) == 0x06A8, dirty_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_count) == 0x06B0, mig_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.num_migs) == 0x06B8, num_migs);
tdx_static_assert(offsetof(tdcs_t, migration_fields.num_migrated_vcpus) == 0x06BC, num_migrated_vcpus);
tdx_static_assert(offsetof(tdcs_t, migration_fields.pre_import_uuid) == 0x06C0, pre_import_uuid);
tdx_static_assert(offsetof(tdcs_t, service_td_fields.servtd_hash) == 0x1280, servtd_hash);
tdx_static_assert(offsetof(tdcs_t, service_td_fields.servtd_num) == 0x12B0, servtd_num);
tdx_static_assert(offsetof(tdcs_t, service_td_fields.servtd_bindings_table) == 0x1310, servtd_bindings_table);
tdx_static_assert(offsetof(tdcs_t, migsc_links) == 0x8000, migsc_links);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.curr_iotlb_cnt) == 0x3000, curr_iotlb_cnt);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.prev_iotlb_cnt) == 0x3008, prev_iotlb_cnt);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.req_active) == 0x3010, req_active);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.req_num) == 0x3011, req_num);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.req_iommu_bm) == 0x3020, req_iommu_bm);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.status_complete_wr) == 0x3030, status_complete_wr);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.status_complete_gpa) == 0x3038, status_complete_gpa);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.status_complete_data) == 0x3034, status_complete_data);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.iotlb_track_array) == 0x3050, iotlb_track_array);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.iotlb_committed) == 0x3450, iotlb_committed);
tdx_static_assert(offsetof(tdcs_t, tdxio_fields.iotlb_complete) == 0x34D0, iotlb_complete);
tdx_static_assert(offsetof(tdcs_t, x2apic_ids) == 0x1680, x2apic_ids);
tdx_static_assert(offsetof(tdcs_t, msr_bitmaps) == 0x5000, msr_bitmaps);
tdx_static_assert(offsetof(tdcs_t, sept_root) == 0x6000, sept_root);
tdx_static_assert(offsetof(tdcs_t, l2_sept_root_1) == 0x9000, l2_sept_root_1);
tdx_static_assert(offsetof(tdcs_t, l2_sept_root_2) == 0xA000, l2_sept_root_2);
tdx_static_assert(offsetof(tdcs_t, l2_sept_root_3) == 0xB000, l2_sept_root_3);
