// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "f0950101"
 *  Spreadsheet Format Version - '28'
 **/

#include "data_structures/tdx_tdvps.h"

tdx_static_assert(offsetof(tdvps_t, vapic.vapic) == 0x2000, vapic);
tdx_static_assert(offsetof(tdvps_t, ve_info.exit_reason) == 0x0000, exit_reason);
tdx_static_assert(offsetof(tdvps_t, ve_info.valid) == 0x0004, valid);
tdx_static_assert(offsetof(tdvps_t, ve_info.exit_qualification) == 0x0008, exit_qualification);
tdx_static_assert(offsetof(tdvps_t, ve_info.gla) == 0x0010, gla);
tdx_static_assert(offsetof(tdvps_t, ve_info.gpa) == 0x0018, gpa);
tdx_static_assert(offsetof(tdvps_t, ve_info.eptp_index) == 0x0020, eptp_index);
tdx_static_assert(offsetof(tdvps_t, ve_info.instruction_length) == 0x0024, instruction_length);
tdx_static_assert(offsetof(tdvps_t, ve_info.instruction_information) == 0x0028, instruction_information);
tdx_static_assert(offsetof(tdvps_t, ve_info.ve_category) == 0x002C, ve_category);
tdx_static_assert(offsetof(tdvps_t, ve_info.interruptibility_state) == 0x0038, interruptibility_state);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rax) == 0x0980, rax);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rcx) == 0x0988, rcx);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rdx) == 0x0990, rdx);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rbx) == 0x0998, rbx);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rsp) == 0x09A0, rsp);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rbp) == 0x09A8, rbp);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rsi) == 0x09B0, rsi);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.rdi) == 0x09B8, rdi);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r8) == 0x09C0, r8);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r9) == 0x09C8, r9);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r10) == 0x09D0, r10);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r11) == 0x09D8, r11);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r12) == 0x09E0, r12);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r13) == 0x09E8, r13);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r14) == 0x09F0, r14);
tdx_static_assert(offsetof(tdvps_t, guest_state.gpr_state.r15) == 0x09F8, r15);
tdx_static_assert(offsetof(tdvps_t, guest_state.dr0) == 0x0A00, dr0);
tdx_static_assert(offsetof(tdvps_t, guest_state.dr1) == 0x0A08, dr1);
tdx_static_assert(offsetof(tdvps_t, guest_state.dr2) == 0x0A10, dr2);
tdx_static_assert(offsetof(tdvps_t, guest_state.dr3) == 0x0A18, dr3);
tdx_static_assert(offsetof(tdvps_t, guest_state.dr6) == 0x0A20, dr6);
tdx_static_assert(offsetof(tdvps_t, guest_state.xcr0) == 0x0A28, xcr0);
tdx_static_assert(offsetof(tdvps_t, guest_state.cr2) == 0x0A30, cr2);
tdx_static_assert(offsetof(tdvps_t, guest_state.vcpu_state_details) == 0x0A78, vcpu_state_details);
tdx_static_assert(offsetof(tdvps_t, guest_extension_state.xbuff) == 0x3000, xbuff);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.msr_smi_count) == 0x0CE0, msr_smi_count);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_spec_ctrl) == 0x0A80, ia32_spec_ctrl);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_umwait_control) == 0x0A88, ia32_umwait_control);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_tsx_ctrl) == 0x0A90, ia32_tsx_ctrl);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_pmc_gp_cfg_ax) == 0x0A98, ia32_pmc_gp_cfg_ax);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_misc_enable) == 0x0CD8, ia32_misc_enable);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.msr_offcore_rspx) == 0x0AD8, msr_offcore_rspx);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_xfd) == 0x0AE8, ia32_xfd);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_xfd_err) == 0x0AF0, ia32_xfd_err);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_pmc_fx_ctrx) == 0x0AF8, ia32_pmc_fx_ctrx);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_perf_metrics) == 0x0B30, ia32_perf_metrics);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_fixed_ctr_ctrl) == 0x0B38, ia32_fixed_ctr_ctrl);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_perf_global_status) == 0x0B40, ia32_perf_global_status);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_pebs_enable) == 0x0B48, ia32_pebs_enable);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.msr_pebs_data_cfg) == 0x0B50, msr_pebs_data_cfg);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.msr_pebs_ld_lat) == 0x0B58, msr_pebs_ld_lat);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.msr_pebs_frontend) == 0x0B60, msr_pebs_frontend);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_pmc_gp_ctrx) == 0x0B68, ia32_pmc_gp_ctrx);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_ds_area) == 0x0BA8, ia32_ds_area);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_xss) == 0x0C70, ia32_xss);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_lbr_depth) == 0x0C78, ia32_lbr_depth);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_uarch_misc_ctl) == 0x0C80, ia32_uarch_misc_ctl);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_star) == 0x0C88, ia32_star);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_lstar) == 0x0C90, ia32_lstar);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_fmask) == 0x0C98, ia32_fmask);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_kernel_gs_base) == 0x0CA0, ia32_kernel_gs_base);
tdx_static_assert(offsetof(tdvps_t, guest_msr_state.ia32_tsc_aux) == 0x0CA8, ia32_tsc_aux);
tdx_static_assert(offsetof(tdvps_t, management.vcpu_state) == 0x0100, vcpu_state);
tdx_static_assert(offsetof(tdvps_t, management.vcpu_index) == 0x0104, vcpu_index);
tdx_static_assert(offsetof(tdvps_t, management.num_tdvps_pages) == 0x0109, num_tdvps_pages);
tdx_static_assert(offsetof(tdvps_t, management.assoc_lpid) == 0x01D0, assoc_lpid);
tdx_static_assert(offsetof(tdvps_t, management.vcpu_epoch) == 0x01D8, vcpu_epoch);
tdx_static_assert(offsetof(tdvps_t, management.cpuid_supervisor_ve) == 0x01E0, cpuid_supervisor_ve);
tdx_static_assert(offsetof(tdvps_t, management.cpuid_user_ve) == 0x01E1, cpuid_user_ve);
tdx_static_assert(offsetof(tdvps_t, management.last_exit_tsc) == 0x01E8, last_exit_tsc);
tdx_static_assert(offsetof(tdvps_t, management.pend_nmi) == 0x01F0, pend_nmi);
tdx_static_assert(offsetof(tdvps_t, management.xfam_deprecated) == 0x01F8, xfam_deprecated);
tdx_static_assert(offsetof(tdvps_t, management.last_epf_gpa_list_idx) == 0x0200, last_epf_gpa_list_idx);
tdx_static_assert(offsetof(tdvps_t, management.possibly_epf_stepping) == 0x0201, possibly_epf_stepping);
tdx_static_assert(offsetof(tdvps_t, management.last_td_exit) == 0x0101, last_td_exit);
tdx_static_assert(offsetof(tdvps_t, management.tdvps_page_pa) == 0x0110, tdvps_page_pa);
tdx_static_assert(offsetof(tdvps_t, management.hp_lock_busy_start) == 0x0208, hp_lock_busy_start);
tdx_static_assert(offsetof(tdvps_t, management.hp_lock_busy) == 0x0210, hp_lock_busy);
tdx_static_assert(offsetof(tdvps_t, management.last_seamdb_index) == 0x0218, last_seamdb_index);
tdx_static_assert(offsetof(tdvps_t, management.nmi_unblocking_due_to_iret) == 0x01F1, nmi_unblocking_due_to_iret);
tdx_static_assert(offsetof(tdvps_t, management.curr_vm) == 0x0220, curr_vm);
tdx_static_assert(offsetof(tdvps_t, management.l2_exit_host_routing) == 0x0222, l2_exit_host_routing);
tdx_static_assert(offsetof(tdvps_t, management.vm_launched) == 0x0224, vm_launched);
tdx_static_assert(offsetof(tdvps_t, management.lp_dependent_hpa_updated) == 0x0228, lp_dependent_hpa_updated);
tdx_static_assert(offsetof(tdvps_t, management.module_dependent_fields_updated) == 0x022C, module_dependent_fields_updated);
tdx_static_assert(offsetof(tdvps_t, management.l2_ctls) == 0x0238, l2_ctls);
tdx_static_assert(offsetof(tdvps_t, management.l2_debug_ctls) == 0x0258, l2_debug_ctls);
tdx_static_assert(offsetof(tdvps_t, management.tsc_deadline) == 0x0278, tsc_deadline);
tdx_static_assert(offsetof(tdvps_t, management.shadow_tsc_deadline) == 0x0298, shadow_tsc_deadline);
tdx_static_assert(offsetof(tdvps_t, management.base_l2_cr0_guest_host_mask) == 0x02B8, base_l2_cr0_guest_host_mask);
tdx_static_assert(offsetof(tdvps_t, management.base_l2_cr0_read_shadow) == 0x02C0, base_l2_cr0_read_shadow);
tdx_static_assert(offsetof(tdvps_t, management.base_l2_cr4_guest_host_mask) == 0x02C8, base_l2_cr4_guest_host_mask);
tdx_static_assert(offsetof(tdvps_t, management.base_l2_cr4_read_shadow) == 0x02D0, base_l2_cr4_read_shadow);
tdx_static_assert(offsetof(tdvps_t, management.shadow_cr0_guest_host_mask) == 0x02D8, shadow_cr0_guest_host_mask);
tdx_static_assert(offsetof(tdvps_t, management.shadow_cr0_read_shadow) == 0x02F8, shadow_cr0_read_shadow);
tdx_static_assert(offsetof(tdvps_t, management.shadow_cr4_guest_host_mask) == 0x0318, shadow_cr4_guest_host_mask);
tdx_static_assert(offsetof(tdvps_t, management.shadow_cr4_read_shadow) == 0x0338, shadow_cr4_read_shadow);
tdx_static_assert(offsetof(tdvps_t, management.shadow_instruction_timeout_control) == 0x0358, shadow_instruction_timeout_control);
tdx_static_assert(offsetof(tdvps_t, management.shadow_pid_hpa) == 0x0368, shadow_pid_hpa);
tdx_static_assert(offsetof(tdvps_t, management.shadow_pinbased_exec_ctls) == 0x0388, shadow_pinbased_exec_ctls);
tdx_static_assert(offsetof(tdvps_t, management.shadow_ple_gap) == 0x0398, shadow_ple_gap);
tdx_static_assert(offsetof(tdvps_t, management.shadow_ple_window) == 0x03A8, shadow_ple_window);
tdx_static_assert(offsetof(tdvps_t, management.shadow_posted_int_notification_vector) == 0x03B8, shadow_posted_int_notification_vector);
tdx_static_assert(offsetof(tdvps_t, management.shadow_procbased_exec_ctls2) == 0x03C0, shadow_procbased_exec_ctls2);
tdx_static_assert(offsetof(tdvps_t, management.shadow_shared_eptp) == 0x03D0, shadow_shared_eptp);
tdx_static_assert(offsetof(tdvps_t, management.l2_enter_guest_state_gpa) == 0x03F0, l2_enter_guest_state_gpa);
tdx_static_assert(offsetof(tdvps_t, management.l2_enter_guest_state_hpa) == 0x0410, l2_enter_guest_state_hpa);
tdx_static_assert(offsetof(tdvps_t, management.ve_info_gpa) == 0x0430, ve_info_gpa);
tdx_static_assert(offsetof(tdvps_t, management.ve_info_hpa) == 0x0450, ve_info_hpa);
tdx_static_assert(offsetof(tdvps_t, management.l2_vapic_gpa) == 0x0470, l2_vapic_gpa);
tdx_static_assert(offsetof(tdvps_t, management.l2_vapic_hpa) == 0x0490, l2_vapic_hpa);
tdx_static_assert(offsetof(tdvps_t, cpuid_control) == 0x0900, cpuid_control);
tdx_static_assert(offsetof(tdvps_t, last_epf_gpa_list) == 0x0700, last_epf_gpa_list);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[0].l2_vmcs) == 0x6000, l2_vmcs);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[0].l2_msr_bitmaps) == 0x7000, l2_msr_bitmaps);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[0].l2_shadow_msr_bitmaps) == 0x8000, l2_shadow_msr_bitmaps);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[1].l2_vmcs) == 0x9000, l2_vmcs);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[1].l2_msr_bitmaps) == 0xA000, l2_msr_bitmaps);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[1].l2_shadow_msr_bitmaps) == 0xB000, l2_shadow_msr_bitmaps);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[2].l2_vmcs) == 0xC000, l2_vmcs);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[2].l2_msr_bitmaps) == 0xD000, l2_msr_bitmaps);
tdx_static_assert(offsetof(tdvps_t, l2_vm_ctrl[2].l2_shadow_msr_bitmaps) == 0xE000, l2_shadow_msr_bitmaps);
