// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  Spreadsheet Format Version - '28'
 **/

#include "./tdvps_fields_lookup.h"


const md_lookup_t tdvps_lookup[MAX_NUM_TDVPS_LOOKUP] = {
 {
   // VAPIC // 0
   .field_id =  { .raw  = 0x0120000300000000 }, 
   .num_of_fields = 128, .num_of_elem = 1, .offset = 0x2000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // EXIT_REASON // 1
   .field_id =  { .raw  = 0x0220000200000000 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // VALID // 2
   .field_id =  { .raw  = 0x0220000200000001 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0004, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // EXIT_QUALIFICATION // 3
   .field_id =  { .raw  = 0x0220000300000002 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0008, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // GLA // 4
   .field_id =  { .raw  = 0x0220000300000003 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0010, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // GPA // 5
   .field_id =  { .raw  = 0x0220000300000004 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0018, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // EPTP_INDEX // 6
   .field_id =  { .raw  = 0x0220000100000005 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0020, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // INSTRUCTION_LENGTH // 7
   .field_id =  { .raw  = 0x8220000200000010 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0024, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // INSTRUCTION_INFORMATION // 8
   .field_id =  { .raw  = 0x8220000200000011 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0028, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // VE_CATEGORY // 9
   .field_id =  { .raw  = 0x8220000000000013 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x002C, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // INTERRUPTIBILITY_STATE // 10
   .field_id =  { .raw  = 0x8220000200000014 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0038, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_MEO 
 },
 {
   // RAX // 11
   .field_id =  { .raw  = 0x1020000300000000 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0980, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // RCX // 12
   .field_id =  { .raw  = 0x1020000300000001 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0988, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // RDX // 13
   .field_id =  { .raw  = 0x1020000300000002 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0990, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // RBX // 14
   .field_id =  { .raw  = 0x1020000300000003 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0998, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // RSP_PLACEHOLDER // 15
   .field_id =  { .raw  = 0x1020000300000004 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09A0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // RBP // 16
   .field_id =  { .raw  = 0x1020000300000005 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09A8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // RSI // 17
   .field_id =  { .raw  = 0x1020000300000006 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09B0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // RDI // 18
   .field_id =  { .raw  = 0x1020000300000007 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09B8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R8 // 19
   .field_id =  { .raw  = 0x1020000300000008 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09C0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R9 // 20
   .field_id =  { .raw  = 0x1020000300000009 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09C8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R10 // 21
   .field_id =  { .raw  = 0x102000030000000A }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09D0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R11 // 22
   .field_id =  { .raw  = 0x102000030000000B }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09D8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R12 // 23
   .field_id =  { .raw  = 0x102000030000000C }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09E0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R13 // 24
   .field_id =  { .raw  = 0x102000030000000D }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09E8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R14 // 25
   .field_id =  { .raw  = 0x102000030000000E }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09F0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // R15 // 26
   .field_id =  { .raw  = 0x102000030000000F }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x09F8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // DR0 // 27
   .field_id =  { .raw  = 0x1120000300000000 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A00, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // DR1 // 28
   .field_id =  { .raw  = 0x1120000300000001 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A08, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // DR2 // 29
   .field_id =  { .raw  = 0x1120000300000002 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A10, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // DR3 // 30
   .field_id =  { .raw  = 0x1120000300000003 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A18, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // DR6 // 31
   .field_id =  { .raw  = 0x1120000300000006 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A20, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (4294967295ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // XCR0 // 32
   .field_id =  { .raw  = 0x1120000300000020 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A28, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // CR2 // 33
   .field_id =  { .raw  = 0x1120000300000028 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A30, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // VCPU_STATE_DETAILS // 34
   .field_id =  { .raw  = 0x9120000300000100 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A78, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_MEO 
 },
 {
   // XBUFF // 35
   .field_id =  { .raw  = 0x1220000300000000 }, 
   .num_of_fields = 1536, .num_of_elem = 1, .offset = 0x3000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // MSR_SMI_COUNT // 36
   .field_id =  { .raw  = 0x1320000300000034 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0CE0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_IESMEO 
 },
 {
   // IA32_SPEC_CTRL // 37
   .field_id =  { .raw  = 0x1320000300000048 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A80, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_UMWAIT_CONTROL // 38
   .field_id =  { .raw  = 0x13200003000000E1 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A88, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_TSX_CTRL // 39
   .field_id =  { .raw  = 0x1320000300000122 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0A90, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_PMC_GP_CFG_Ax // 40
   .field_id =  { .raw  = 0x1320000300000186 }, 
   .num_of_fields = 8, .num_of_elem = 1, .offset = 0x0A98, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_MISC_ENABLE // 41
   .field_id =  { .raw  = 0x13200003000001A0 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0CD8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_IESMEO 
 },
 {
   // MSR_OFFCORE_RSPx // 42
   .field_id =  { .raw  = 0x13200003000001A6 }, 
   .num_of_fields = 2, .num_of_elem = 1, .offset = 0x0AD8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_XFD // 43
   .field_id =  { .raw  = 0x13200003000001C4 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0AE8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_XFD_ERR // 44
   .field_id =  { .raw  = 0x13200003000001C5 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0AF0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_PMC_FX_CTRx // 45
   .field_id =  { .raw  = 0x1320000300000309 }, 
   .num_of_fields = 7, .num_of_elem = 1, .offset = 0x0AF8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_PERF_METRICS // 46
   .field_id =  { .raw  = 0x1320000300000329 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0B30, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_FIXED_CTR_CTRL // 47
   .field_id =  { .raw  = 0x132000030000038D }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0B38, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_PERF_GLOBAL_STATUS // 48
   .field_id =  { .raw  = 0x132000030000038E }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0B40, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_PEBS_ENABLE // 49
   .field_id =  { .raw  = 0x13200003000003F1 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0B48, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // MSR_PEBS_DATA_CFG // 50
   .field_id =  { .raw  = 0x13200003000003F2 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0B50, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // MSR_PEBS_LD_LAT // 51
   .field_id =  { .raw  = 0x13200003000003F6 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0B58, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // MSR_PEBS_FRONTEND // 52
   .field_id =  { .raw  = 0x13200003000003F7 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0B60, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_PMC_GP_CTRx // 53
   .field_id =  { .raw  = 0x13200003000004C1 }, 
   .num_of_fields = 8, .num_of_elem = 1, .offset = 0x0B68, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_DS_AREA // 54
   .field_id =  { .raw  = 0x1320000300000600 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0BA8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_XSS // 55
   .field_id =  { .raw  = 0x1320000300000DA0 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0C70, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_LBR_DEPTH // 56
   .field_id =  { .raw  = 0x13200003000014CF }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0C78, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_UARCH_MISC_CTL // 57
   .field_id =  { .raw  = 0x1320000300001B01 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0C80, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_STAR // 58
   .field_id =  { .raw  = 0x1320000300002081 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0C88, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_LSTAR // 59
   .field_id =  { .raw  = 0x1320000300002082 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0C90, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_FMASK // 60
   .field_id =  { .raw  = 0x1320000300002084 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0C98, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_KERNEL_GS_BASE // 61
   .field_id =  { .raw  = 0x1320000300002102 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0CA0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // IA32_TSC_AUX // 62
   .field_id =  { .raw  = 0x1320000300002103 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0CA8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // VCPU_STATE // 63
   .field_id =  { .raw  = 0xA020000000000000 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0100, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // VCPU_INDEX // 64
   .field_id =  { .raw  = 0xA020000200000002 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0104, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // NUM_TDVPS_PAGES // 65
   .field_id =  { .raw  = 0xA020000000000003 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0109, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // ASSOC_LPID // 66
   .field_id =  { .raw  = 0xA020000200000004 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01D0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // VCPU_EPOCH // 67
   .field_id =  { .raw  = 0xA020000300000006 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01D8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // CPUID_SUPERVISOR_VE // 68
   .field_id =  { .raw  = 0xA020000000000007 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01E0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (-1ULL & 0xFFULL), .guest_wr_mask = (-1ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // CPUID_USER_VE // 69
   .field_id =  { .raw  = 0xA020000000000008 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01E1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (-1ULL & 0xFFULL), .guest_wr_mask = (-1ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // LAST_EXIT_TSC // 70
   .field_id =  { .raw  = 0xA02000030000000A }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01E8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // PEND_NMI // 71
   .field_id =  { .raw  = 0x202000000000000B }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01F0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFULL), .prod_wr_mask = (-1ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (-1ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // XFAM_DEPRECATED // 72
   .field_id =  { .raw  = 0x202000030000000C }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01F8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // LAST_EPF_GPA_LIST_IDX // 73
   .field_id =  { .raw  = 0xA02000000000000D }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0200, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // POSSIBLY_EPF_STEPPING // 74
   .field_id =  { .raw  = 0xA02000000000000E }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0201, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // LAST_TD_EXIT // 75
   .field_id =  { .raw  = 0xA02000000000000F }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0101, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // TDVPS_PAGE_PA // 76
   .field_id =  { .raw  = 0xA020000300000010 }, 
   .num_of_fields = 15, .num_of_elem = 1, .offset = 0x0110, .attributes = { .raw = 0x5 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // HP_LOCK_BUSY_START // 77
   .field_id =  { .raw  = 0xA020000300000030 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0208, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // HP_LOCK_BUSY // 78
   .field_id =  { .raw  = 0xA020000000000031 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0210, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // LAST_SEAMDB_INDEX // 79
   .field_id =  { .raw  = 0xA020000300000032 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0218, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // NMI_UNBLOCKING_DUE_TO_IRET // 80
   .field_id =  { .raw  = 0xA020000000000040 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x01F1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // CURR_VM // 81
   .field_id =  { .raw  = 0xA020000100000041 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0220, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // L2_EXIT_HOST_ROUTING // 82
   .field_id =  { .raw  = 0xA020000000000042 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x0222, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (-1ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // VM_LAUNCHED // 83
   .field_id =  { .raw  = 0xA020000000000044 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0224, .attributes = { .raw = 0x30 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // LP_DEPENDENT_HPA_UPDATED // 84
   .field_id =  { .raw  = 0xA020000000000048 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0228, .attributes = { .raw = 0x30 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // MODULE_DEPENDENT_FIELDS_UPDATED // 85
   .field_id =  { .raw  = 0xA02000000000004C }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x022C, .attributes = { .raw = 0x30 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // L2_CTLS // 86
   .field_id =  { .raw  = 0xA020000300000050 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0238, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (3ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (3ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (3ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // L2_DEBUG_CTLS // 87
   .field_id =  { .raw  = 0xA020000300000054 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0258, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (7ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (7ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // TSC_DEADLINE // 88
   .field_id =  { .raw  = 0xA020000300000058 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0278, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // SHADOW_TSC_DEADLINE // 89
   .field_id =  { .raw  = 0xA02000030000005C }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0298, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // BASE_L2_CR0_GUEST_HOST_MASK // 90
   .field_id =  { .raw  = 0xA020000300000080 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x02B8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (18446744072098938847ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // BASE_L2_CR0_READ_SHADOW // 91
   .field_id =  { .raw  = 0xA020000300000081 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x02C0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (18446744072098938847ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // BASE_L2_CR4_GUEST_HOST_MASK // 92
   .field_id =  { .raw  = 0xA020000300000082 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x02C8, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (18446744073709526975ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // BASE_L2_CR4_READ_SHADOW // 93
   .field_id =  { .raw  = 0xA020000300000083 }, 
   .num_of_fields = 1, .num_of_elem = 1, .offset = 0x02D0, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (18446744072098938847ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_CR0_GUEST_HOST_MASK // 94
   .field_id =  { .raw  = 0xA020000300000084 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x02D8, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_CR0_READ_SHADOW // 95
   .field_id =  { .raw  = 0xA020000300000088 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x02F8, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_CR4_GUEST_HOST_MASK // 96
   .field_id =  { .raw  = 0xA02000030000008C }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0318, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_CR4_READ_SHADOW // 97
   .field_id =  { .raw  = 0xA020000300000090 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0338, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_INSTRUCTION_TIMEOUT_CONTROL // 98
   .field_id =  { .raw  = 0xA020000200000094 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0358, .attributes = { .raw = 0x30 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_PID_HPA // 99
   .field_id =  { .raw  = 0xA020000300000098 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0368, .attributes = { .raw = 0x19 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_PINBASED_EXEC_CTLS // 100
   .field_id =  { .raw  = 0xA02000020000009C }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0388, .attributes = { .raw = 0x10 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_PLE_GAP // 101
   .field_id =  { .raw  = 0xA0200002000000A4 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0398, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_PLE_WINDOW // 102
   .field_id =  { .raw  = 0xA0200002000000A8 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x03A8, .attributes = { .raw = 0x20 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_POSTED_INT_NOTIFICATION_VECTOR // 103
   .field_id =  { .raw  = 0xA0200001000000AC }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x03B8, .attributes = { .raw = 0x10 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_PROCBASED_EXEC_CTLS2 // 104
   .field_id =  { .raw  = 0xA0200002000000B0 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x03C0, .attributes = { .raw = 0x30 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // SHADOW_SHARED_EPTP // 105
   .field_id =  { .raw  = 0xA0200003000000B4 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x03D0, .attributes = { .raw = 0x39 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // L2_ENTER_GUEST_STATE_GPA // 106
   .field_id =  { .raw  = 0xA020000300000100 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x03F0, .attributes = { .raw = 0x26 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // L2_ENTER_GUEST_STATE_HPA // 107
   .field_id =  { .raw  = 0xA020000300000104 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0410, .attributes = { .raw = 0x25 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // VE_INFO_GPA // 108
   .field_id =  { .raw  = 0xA020000300000108 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0430, .attributes = { .raw = 0x26 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_NONE 
 },
 {
   // VE_INFO_HPA // 109
   .field_id =  { .raw  = 0xA02000030000010C }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0450, .attributes = { .raw = 0x25 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // L2_VAPIC_GPA // 110
   .field_id =  { .raw  = 0xA020000300000110 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0470, .attributes = { .raw = 0x26 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // L2_VAPIC_HPA // 111
   .field_id =  { .raw  = 0xA020000300000114 }, 
   .num_of_fields = 4, .num_of_elem = 1, .offset = 0x0490, .attributes = { .raw = 0x25 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // CPUID_CONTROL // 112
   .field_id =  { .raw  = 0xA120000000000000 }, 
   .num_of_fields = 128, .num_of_elem = 1, .offset = 0x0900, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (-1ULL & 0xFFULL), .guest_wr_mask = (3ULL & 0xFFULL),
   .export_mask = (-1ULL & 0xFFULL), .import_mask = (3ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // LAST_EPF_GPA_LIST // 113
   .field_id =  { .raw  = 0xA220000300000200 }, 
   .num_of_fields = 32, .num_of_elem = 1, .offset = 0x0700, .attributes = { .raw = 0x6 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = false, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // L2_VMCS_1 // 114
   .field_id =  { .raw  = 0x2420000000000000 }, 
   .num_of_fields = 4096, .num_of_elem = 1, .offset = 0x6000,
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (0ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false 
 },
 {
   // L2_MSR_BITMAPS_1 // 115
   .field_id =  { .raw  = 0x2520000300000000 }, 
   .num_of_fields = 512, .num_of_elem = 1, .offset = 0x7000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // L2_SHADOW_MSR_BITMAPS_1 // 116
   .field_id =  { .raw  = 0xA620000300000000 }, 
   .num_of_fields = 512, .num_of_elem = 1, .offset = 0x8000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // L2_VMCS_2 // 117
   .field_id =  { .raw  = 0x2C20000000000000 }, 
   .num_of_fields = 4096, .num_of_elem = 1, .offset = 0x9000,
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (0ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false 
 },
 {
   // L2_MSR_BITMAPS_2 // 118
   .field_id =  { .raw  = 0x2D20000300000000 }, 
   .num_of_fields = 512, .num_of_elem = 1, .offset = 0xA000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // L2_SHADOW_MSR_BITMAPS_2 // 119
   .field_id =  { .raw  = 0xAE20000300000000 }, 
   .num_of_fields = 512, .num_of_elem = 1, .offset = 0xB000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 },
 {
   // L2_VMCS_3 // 120
   .field_id =  { .raw  = 0x3420000000000000 }, 
   .num_of_fields = 4096, .num_of_elem = 1, .offset = 0xC000,
   .prod_rd_mask = (0ULL & 0xFFULL), .prod_wr_mask = (0ULL & 0xFFULL),
   .dbg_rd_mask = (0ULL & 0xFFULL), .dbg_wr_mask = (0ULL & 0xFFULL),
   .guest_rd_mask = (0ULL & 0xFFULL), .guest_wr_mask = (0ULL & 0xFFULL),
   .export_mask = (0ULL & 0xFFULL), .import_mask = (0ULL & 0xFFULL),
   .special_rd_handling = false, .special_wr_handling = false 
 },
 {
   // L2_MSR_BITMAPS_3 // 121
   .field_id =  { .raw  = 0x3520000300000000 }, 
   .num_of_fields = 512, .num_of_elem = 1, .offset = 0xD000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = true,
   .mig_export = MIG_ME, .mig_import = MIG_ME 
 },
 {
   // L2_SHADOW_MSR_BITMAPS_3 // 122
   .field_id =  { .raw  = 0xB620000300000000 }, 
   .num_of_fields = 512, .num_of_elem = 1, .offset = 0xE000, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .guest_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .guest_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .special_rd_handling = true, .special_wr_handling = false,
   .mig_export = MIG_NONE, .mig_import = MIG_IES 
 }
};

