// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  Spreadsheet Format Version - '10'
 **/

#include "./cpuid_configurations.h"

// Lookup table first MAX_NUM_CPUID_CONFIG entries will be in the same order as in cpuid_configurable table

const cpuid_lookup_t cpuid_lookup[MAX_NUM_CPUID_LOOKUP] = {
 [10] = { .leaf_subleaf = {.leaf = 0x0, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .verify_value = { .ebx = 0x756e6547, .ecx = 0x6c65746e, .edx = 0x49656e69 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed1 = { .eax = 0x23 },
  .fixed0_or_dynamic = { .eax = 0xffffffdc },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [0] = { .leaf_subleaf = {.leaf = 0x1, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .ebx = 0xff00, .ecx = 0x47faa217, .edx = 0x1fa9fbff },
  .verify_value = { .ebx = 0x800, .ecx = 0x47faa217, .edx = 0x1fa9fbff },
  .verify_same = { .eax = 0xf000c000, .ebx = 0xffff, .ecx = 0xf7ffff9f, .edx = 0xffffffff },
  .fixed1 = { .ecx = 0x80000000, .edx = 0x200 },
  .fixed0_or_dynamic = { .eax = 0xf000c000, .ebx = 0xff0000ff, .ecx = 0x8010060, .edx = 0x40120400 },
  .config_index = 0
  },
 [72] = { .leaf_subleaf = {.leaf = 0x2, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed1 = { .eax = 0xfeff01, .ebx = 0x0, .ecx = 0x0, .edx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xff0100fe, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [11] = { .leaf_subleaf = {.leaf = 0x3, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [1] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x0},
  .valid_entry = true,
  .verify_mask = { .ebx = 0xfff },
  .verify_value = { .ebx = 0x3f },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0xfffffff8 },
  .config_index = 1
  },
 [2] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x1},
  .valid_entry = true,
  .verify_mask = { .ebx = 0xfff },
  .verify_value = { .ebx = 0x3f },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0xfffffff8 },
  .config_index = 2
  },
 [3] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x2},
  .valid_entry = true,
  .verify_mask = { .ebx = 0xfff },
  .verify_value = { .ebx = 0x3f },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0xfffffff8 },
  .config_index = 3
  },
 [4] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x3},
  .valid_entry = true,
  .verify_mask = { .eax = 0xe0, .ebx = 0xfff, .edx = 0x1 },
  .verify_value = { .eax = 0x60, .ebx = 0x3f, .edx = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0x3c00, .edx = 0xfffffff8 },
  .config_index = 4
  },
 [12] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x4},
  .valid_entry = true,
  .verify_mask = { .eax = 0x1f },
  .verify_value = { .eax = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [63] = { .leaf_subleaf = {.leaf = 0x5, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffff0000, .ebx = 0xffff0000, .ecx = 0xfffffffc },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [13] = { .leaf_subleaf = {.leaf = 0x6, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .eax = 0x800000 },
  .verify_value = { .eax = 0x0 },
  .verify_same = { .eax = 0x800000 },
  .fixed1 = { .eax = 0x4 },
  .fixed0_or_dynamic = { .eax = 0xfffffffb, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [5] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x0},
  .valid_entry = true,
  .verify_mask = { .eax = 0xffffffff, .ebx = 0x219424c3, .ecx = 0x99000000, .edx = 0xfc082600 },
  .verify_value = { .eax = 0x2, .ebx = 0x219424c3, .ecx = 0x99000000, .edx = 0xfc080400 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xfffffffb, .ecx = 0xbfc17f6f, .edx = 0xffebffff },
  .fixed0_or_dynamic = { .ebx = 0x404006, .ecx = 0x643e8010, .edx = 0x2298c3 },
  .config_index = 5
  },
 [6] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x1},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xfb77e20f, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xfffdbbcf },
  .config_index = 6
  },
 [14] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x2},
  .valid_entry = true,
  .verify_mask = { .edx = 0x17 },
  .verify_value = { .edx = 0x17 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffc0 },
  .config_index = 10
  },
 [15] = { .leaf_subleaf = {.leaf = 0x8, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [7] = { .leaf_subleaf = {.leaf = 0xa, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .eax = 0xff00, .ecx = 0xffffff80, .edx = 0x8000 },
  .verify_value = { .eax = 0x800, .ecx = 0x0, .edx = 0x8000 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffff6000 },
  .config_index = 7
  },
 [64] = { .leaf_subleaf = {.leaf = 0xb, .subleaf = 0x0},
  .valid_entry = true,
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [65] = { .leaf_subleaf = {.leaf = 0xb, .subleaf = 0x1},
  .valid_entry = true,
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [66] = { .leaf_subleaf = {.leaf = 0xb, .subleaf = 0x2},
  .valid_entry = true,
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffff00, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [16] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x0},
  .valid_entry = true,
  .verify_mask = { .eax = 0x3 },
  .verify_value = { .eax = 0x3 },
  .verify_same = { .eax = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xfff9fd18, .ebx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [17] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x1},
  .valid_entry = true,
  .verify_mask = { .eax = 0xf, .ecx = 0x1800 },
  .verify_value = { .eax = 0xf, .ecx = 0x1800 },
  .verify_same = { .eax = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffffffff, .ecx = 0xffff26ff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [18] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x2},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [19] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x3},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [20] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x4},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [21] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x5},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [22] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x6},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [23] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x7},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [24] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x8},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [25] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x9},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [26] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xa},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [27] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xb},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [28] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xc},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [29] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xd},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [30] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xe},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [31] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xf},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [32] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x10},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [33] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x11},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [34] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x12},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [35] = { .leaf_subleaf = {.leaf = 0xe, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [36] = { .leaf_subleaf = {.leaf = 0x11, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [37] = { .leaf_subleaf = {.leaf = 0x12, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [38] = { .leaf_subleaf = {.leaf = 0x13, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [39] = { .leaf_subleaf = {.leaf = 0x14, .subleaf = 0x0},
  .valid_entry = true,
  .verify_mask = { .eax = 0xffffffff },
  .verify_value = { .eax = 0x1 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .ebx = 0xfffffe00, .ecx = 0x7ffffff0, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [40] = { .leaf_subleaf = {.leaf = 0x14, .subleaf = 0x1},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xfff8, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [41] = { .leaf_subleaf = {.leaf = 0x15, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed1 = { .eax = 0x1, .ecx = 0x17d7840 },
  .fixed0_or_dynamic = { .eax = 0xfffffffe, .ecx = 0xfe8287bf, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [68] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x0},
  .valid_entry = true,
  .config_index = 19
  },
 [69] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x1},
  .valid_entry = true,
  .config_index = 20
  },
 [70] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x2},
  .valid_entry = true,
  .config_index = 21
  },
 [71] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x3},
  .valid_entry = true,
  .config_index = 22
  },
 [73] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x4},
  .valid_entry = true,
  .config_index = 23
  },
 [74] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x5},
  .valid_entry = true,
  .config_index = 24
  },
 [75] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x6},
  .valid_entry = true,
  .config_index = 25
  },
 [76] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x7},
  .valid_entry = true,
  .config_index = 26
  },
 [77] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x8},
  .valid_entry = true,
  .config_index = 27
  },
 [42] = { .leaf_subleaf = {.leaf = 0x19, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xfffffffe, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = 18
  },
 [67] = { .leaf_subleaf = {.leaf = 0x1a, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [8] = { .leaf_subleaf = {.leaf = 0x1c, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = 8
  },
 [43] = { .leaf_subleaf = {.leaf = 0x1d, .subleaf = 0x0},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [44] = { .leaf_subleaf = {.leaf = 0x1d, .subleaf = 0x1},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [45] = { .leaf_subleaf = {.leaf = 0x1e, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [46] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x0},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff },
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = 12
  },
 [47] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x1},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff },
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = 13
  },
 [48] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x2},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff },
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = 14
  },
 [49] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x3},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff },
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = 15
  },
 [50] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x4},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff },
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = 16
  },
 [51] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x5},
  .valid_entry = true,
  .verify_mask = { .ecx = 0xff00 },
  .verify_value = { .ecx = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff },
  .fixed1 = { .eax = 0x0, .ebx = 0x0, .ecx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0xffffffe0, .ebx = 0xffff0000, .ecx = 0xffff0000, .edx = 0xffffffff },
  .config_index = 17
  },
 [52] = { .leaf_subleaf = {.leaf = 0x20, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [53] = { .leaf_subleaf = {.leaf = 0x21, .subleaf = 0x0},
  .valid_entry = true,
  .fixed1 = { .eax = 0x0, .ebx = 0x65746e49, .ecx = 0x20202020, .edx = 0x5844546c },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0x9a8b91b6, .ecx = 0xdfdfdfdf, .edx = 0xa7bbab93 },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [58] = { .leaf_subleaf = {.leaf = 0x22, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [59] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x0},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xfffffff0, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = 11
  },
 [60] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x1},
  .valid_entry = true,
  .verify_mask = { .eax = 0xffffff00, .ebx = 0xffffff80 },
  .verify_value = { .eax = 0x0, .ebx = 0x0 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [61] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x2},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [62] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x3},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [54] = { .leaf_subleaf = {.leaf = 0x80000000, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed1 = { .eax = 0x80000008 },
  .fixed0_or_dynamic = { .eax = 0x7ffffff7, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [55] = { .leaf_subleaf = {.leaf = 0x80000001, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .ecx = 0x121, .edx = 0x2c100800 },
  .verify_value = { .ecx = 0x121, .edx = 0x2c100800 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xfffffede, .edx = 0xd3efffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [78] = { .leaf_subleaf = {.leaf = 0x80000002, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed1 = { .eax = 0x65746e49, .ebx = 0x4454206c, .ecx = 0x20202058, .edx = 0x0 },
  .fixed0_or_dynamic = { .eax = 0x9a8b91b6, .ebx = 0xbbabdf93, .ecx = 0xdfdfdfa7, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [56] = { .leaf_subleaf = {.leaf = 0x80000006, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .ecx = 0xff },
  .verify_value = { .ecx = 0x40 },
  .verify_same = { .ecx = 0xff },
  .fixed1 = { .ecx = 0x7040 },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0x8fbf, .edx = 0xffffffff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [57] = { .leaf_subleaf = {.leaf = 0x80000007, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .edx = 0x100 },
  .verify_value = { .edx = 0x100 },
  .verify_same = { .edx = 0x100 },
  .fixed0_or_dynamic = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xfffffeff },
  .config_index = CPUID_CONFIG_NULL_IDX
  },
 [9] = { .leaf_subleaf = {.leaf = 0x80000008, .subleaf = 0xffffffff},
  .valid_entry = true,
  .verify_mask = { .ebx = 0x200 },
  .verify_value = { .ebx = 0x200 },
  .verify_same = { .eax = 0xffffffff, .ebx = 0xffffffff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .fixed0_or_dynamic = { .ebx = 0xfffffdff, .ecx = 0xffffffff, .edx = 0xffffffff },
  .config_index = 9
  }
};

const ordered_cpuid_lookup_t ordered_cpuid_lookup[MAX_NUM_ORDERED_CPUID_LOOKUP] = {
 [0] = { .leaf_subleaf = {.leaf = 0x0, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 10
  },
 [1] = { .leaf_subleaf = {.leaf = 0x1, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 0
  },
 [2] = { .leaf_subleaf = {.leaf = 0x2, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 72
  },
 [3] = { .leaf_subleaf = {.leaf = 0x3, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 11
  },
 [4] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 1
  },
 [5] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 2
  },
 [6] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 3
  },
 [7] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x3},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 4
  },
 [8] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x4},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 12
  },
 [9] = { .leaf_subleaf = {.leaf = 0x5, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 63
  },
 [10] = { .leaf_subleaf = {.leaf = 0x6, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 13
  },
 [11] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 5
  },
 [12] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 6
  },
 [13] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 14
  },
 [14] = { .leaf_subleaf = {.leaf = 0x8, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 15
  },
 [15] = { .leaf_subleaf = {.leaf = 0x9, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [16] = { .leaf_subleaf = {.leaf = 0xa, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 7
  },
 [17] = { .leaf_subleaf = {.leaf = 0xb, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 64
  },
 [18] = { .leaf_subleaf = {.leaf = 0xb, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 65
  },
 [19] = { .leaf_subleaf = {.leaf = 0xb, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 66
  },
 [20] = { .leaf_subleaf = {.leaf = 0xc, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [21] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 16
  },
 [22] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 17
  },
 [23] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 18
  },
 [24] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x3},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 19
  },
 [25] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x4},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 20
  },
 [26] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x5},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 21
  },
 [27] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x6},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 22
  },
 [28] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x7},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 23
  },
 [29] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x8},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 24
  },
 [30] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x9},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 25
  },
 [31] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xa},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 26
  },
 [32] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xb},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 27
  },
 [33] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xc},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 28
  },
 [34] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xd},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 29
  },
 [35] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xe},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 30
  },
 [36] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0xf},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 31
  },
 [37] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x10},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 32
  },
 [38] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x11},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 33
  },
 [39] = { .leaf_subleaf = {.leaf = 0xd, .subleaf = 0x12},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 34
  },
 [40] = { .leaf_subleaf = {.leaf = 0xe, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 35
  },
 [41] = { .leaf_subleaf = {.leaf = 0xf, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [42] = { .leaf_subleaf = {.leaf = 0xf, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [43] = { .leaf_subleaf = {.leaf = 0x10, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [44] = { .leaf_subleaf = {.leaf = 0x10, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [45] = { .leaf_subleaf = {.leaf = 0x10, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [46] = { .leaf_subleaf = {.leaf = 0x10, .subleaf = 0x3},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [47] = { .leaf_subleaf = {.leaf = 0x11, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 36
  },
 [48] = { .leaf_subleaf = {.leaf = 0x12, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 37
  },
 [49] = { .leaf_subleaf = {.leaf = 0x13, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 38
  },
 [50] = { .leaf_subleaf = {.leaf = 0x14, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 39
  },
 [51] = { .leaf_subleaf = {.leaf = 0x14, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 40
  },
 [52] = { .leaf_subleaf = {.leaf = 0x15, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 41
  },
 [53] = { .leaf_subleaf = {.leaf = 0x16, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [54] = { .leaf_subleaf = {.leaf = 0x17, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [55] = { .leaf_subleaf = {.leaf = 0x17, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [56] = { .leaf_subleaf = {.leaf = 0x17, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [57] = { .leaf_subleaf = {.leaf = 0x17, .subleaf = 0x3},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [58] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 68
  },
 [59] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 69
  },
 [60] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 70
  },
 [61] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x3},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 71
  },
 [62] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x4},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 73
  },
 [63] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x5},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 74
  },
 [64] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x6},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 75
  },
 [65] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x7},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 76
  },
 [66] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x8},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 77
  },
 [67] = { .leaf_subleaf = {.leaf = 0x19, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 42
  },
 [68] = { .leaf_subleaf = {.leaf = 0x1a, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 67
  },
 [69] = { .leaf_subleaf = {.leaf = 0x1b, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [70] = { .leaf_subleaf = {.leaf = 0x1b, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [71] = { .leaf_subleaf = {.leaf = 0x1c, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 8
  },
 [72] = { .leaf_subleaf = {.leaf = 0x1d, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 43
  },
 [73] = { .leaf_subleaf = {.leaf = 0x1d, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 44
  },
 [74] = { .leaf_subleaf = {.leaf = 0x1e, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 45
  },
 [75] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 46
  },
 [76] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 47
  },
 [77] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 48
  },
 [78] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x3},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 49
  },
 [79] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x4},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 50
  },
 [80] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x5},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 51
  },
 [81] = { .leaf_subleaf = {.leaf = 0x20, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 52
  },
 [82] = { .leaf_subleaf = {.leaf = 0x21, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 53
  },
 [83] = { .leaf_subleaf = {.leaf = 0x22, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 58
  },
 [84] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x0},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 59
  },
 [85] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x1},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 60
  },
 [86] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x2},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 61
  },
 [87] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x3},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 62
  },
 [88] = { .leaf_subleaf = {.leaf = 0x80000000, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 54
  },
 [89] = { .leaf_subleaf = {.leaf = 0x80000001, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 55
  },
 [90] = { .leaf_subleaf = {.leaf = 0x80000002, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 78
  },
 [91] = { .leaf_subleaf = {.leaf = 0x80000003, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [92] = { .leaf_subleaf = {.leaf = 0x80000004, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [93] = { .leaf_subleaf = {.leaf = 0x80000005, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = (uint32_t)(-1)
  },
 [94] = { .leaf_subleaf = {.leaf = 0x80000006, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 56
  },
 [95] = { .leaf_subleaf = {.leaf = 0x80000007, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = true,
  .index_to_cpuid_lookup = 57
  },
 [96] = { .leaf_subleaf = {.leaf = 0x80000008, .subleaf = 0xffffffff},
  .valid_entry = true,
  .fixed0 = false,
  .index_to_cpuid_lookup = 9
  }
};

const cpuid_configurable_t cpuid_configurable[MAX_NUM_CPUID_CONFIG] = {
 [0] = { .leaf_subleaf = {.leaf = 0x1, .subleaf = 0xffffffff},
  .valid_entry = true,
  .config_direct = { .eax = 0xfff3fff, .ebx = 0xff0000 },
  .allow_direct = { .ecx = 0x31044d88, .edx = 0xb8445080 },
  .lookup_index = 0
  },
 [1] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x0},
  .valid_entry = true,
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0x7 },
  .lookup_index = 1
  },
 [2] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x1},
  .valid_entry = true,
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0x7 },
  .lookup_index = 2
  },
 [3] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x2},
  .valid_entry = true,
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0x7 },
  .lookup_index = 3
  },
 [4] = { .leaf_subleaf = {.leaf = 0x4, .subleaf = 0x3},
  .valid_entry = true,
  .config_direct = { .eax = 0xffffc3ff, .ebx = 0xfffff000, .ecx = 0xffffffff, .edx = 0x7 },
  .lookup_index = 4
  },
 [5] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x0},
  .valid_entry = true,
  .allow_direct = { .ebx = 0xdc2b9b18, .ecx = 0x2417f65, .edx = 0x4005411c },
  .lookup_index = 5
  },
 [6] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x1},
  .valid_entry = true,
  .allow_direct = { .eax = 0x4881db0, .edx = 0x24430 },
  .lookup_index = 6
  },
 [10] = { .leaf_subleaf = {.leaf = 0x7, .subleaf = 0x2},
  .valid_entry = true,
  .allow_direct = { .edx = 0x28 },
  .lookup_index = 14
  },
 [7] = { .leaf_subleaf = {.leaf = 0xa, .subleaf = 0xffffffff},
  .valid_entry = true,
  .lookup_index = 7
  },
 [19] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x0},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 68
  },
 [20] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x1},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 69
  },
 [21] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x2},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 70
  },
 [22] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x3},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 71
  },
 [23] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x4},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 73
  },
 [24] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x5},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 74
  },
 [25] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x6},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 75
  },
 [26] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x7},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 76
  },
 [27] = { .leaf_subleaf = {.leaf = 0x18, .subleaf = 0x8},
  .valid_entry = true,
  .config_direct = { .edx = 0x3ffc000 },
  .lookup_index = 77
  },
 [18] = { .leaf_subleaf = {.leaf = 0x19, .subleaf = 0xffffffff},
  .valid_entry = true,
  .lookup_index = 42
  },
 [8] = { .leaf_subleaf = {.leaf = 0x1c, .subleaf = 0xffffffff},
  .valid_entry = true,
  .allow_direct = { .eax = 0xff },
  .lookup_index = 8
  },
 [12] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x0},
  .valid_entry = true,
  .config_direct = { .eax = 0x1f, .ebx = 0xffff, .ecx = 0xffff },
  .lookup_index = 46
  },
 [13] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x1},
  .valid_entry = true,
  .config_direct = { .eax = 0x1f, .ebx = 0xffff, .ecx = 0xffff },
  .lookup_index = 47
  },
 [14] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x2},
  .valid_entry = true,
  .config_direct = { .eax = 0x1f, .ebx = 0xffff, .ecx = 0xffff },
  .lookup_index = 48
  },
 [15] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x3},
  .valid_entry = true,
  .config_direct = { .eax = 0x1f, .ebx = 0xffff, .ecx = 0xffff },
  .lookup_index = 49
  },
 [16] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x4},
  .valid_entry = true,
  .config_direct = { .eax = 0x1f, .ebx = 0xffff, .ecx = 0xffff },
  .lookup_index = 50
  },
 [17] = { .leaf_subleaf = {.leaf = 0x1f, .subleaf = 0x5},
  .valid_entry = true,
  .config_direct = { .eax = 0x1f, .ebx = 0xffff, .ecx = 0xffff },
  .lookup_index = 51
  },
 [11] = { .leaf_subleaf = {.leaf = 0x23, .subleaf = 0x0},
  .valid_entry = true,
  .allow_direct = { .eax = 0xf },
  .lookup_index = 59
  },
 [9] = { .leaf_subleaf = {.leaf = 0x80000008, .subleaf = 0xffffffff},
  .valid_entry = true,
  .config_direct = { .eax = 0xff },
  .allow_direct = { .ebx = 0x200 },
  .lookup_index = 9
  }
};

const cpuid_config_return_values_t xfam_mask_0x1_0xffffffff[XCR0_MAX_BIT + 1] = {

    [2]={ .ecx = 0x30001000  } ,

};

const cpuid_config_return_values_t xfam_mask_0x7_0x0[XCR0_MAX_BIT + 1] = {

    [2]={ .ebx = 0x20 , .ecx = 0x600  } ,
    [5]={ .ebx = 0xdc230000 , .ecx = 0x5842 , .edx = 0x80010c  } ,
    [6]={ .ebx = 0xdc230000 , .ecx = 0x5842 , .edx = 0x80010c  } ,
    [7]={ .ebx = 0xdc230000 , .ecx = 0x5842 , .edx = 0x80010c  } ,
    [8]={ .ebx = 0x2000000  } ,
    [9]={ .ecx = 0x8  } ,
    [11]={ .ecx = 0x80 , .edx = 0x100000  } ,
    [12]={ .ecx = 0x80 , .edx = 0x100000  } ,
    [14]={ .edx = 0x20  } ,
    [15]={ .edx = 0x80000  } ,
    [17]={ .edx = 0x3400000  } ,
    [18]={ .edx = 0x3400000  } ,

};

const cpuid_config_return_values_t xfam_mask_0x7_0x1[XCR0_MAX_BIT + 1] = {

    [2]={ .eax = 0x800010 , .edx = 0x430  } ,
    [5]={ .eax = 0x20  } ,
    [6]={ .eax = 0x20  } ,
    [7]={ .eax = 0x20  } ,

};

const cpuid_config_return_values_t xfam_mask_0xd_0x0[XCR0_MAX_BIT + 1] = {

    [2]={ .eax = 0x4  } ,
    [5]={ .eax = 0xe0  } ,
    [6]={ .eax = 0xe0  } ,
    [7]={ .eax = 0xe0  } ,
    [9]={ .eax = 0x200  } ,
    [17]={ .eax = 0x60000  } ,
    [18]={ .eax = 0x60000  } ,

};

const cpuid_config_return_values_t xfam_mask_0xd_0x1[XCR0_MAX_BIT + 1] = {

    [8]={ .ecx = 0x100  } ,
    [11]={ .ecx = 0x1800  } ,
    [12]={ .ecx = 0x1800  } ,
    [14]={ .ecx = 0x4000  } ,
    [15]={ .ecx = 0x8000  } ,

};


