// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "f97a493"
 *  Spreadsheet Format Version - '0'
 **/

#ifndef _AUTO_GEN_GLOBAL_CONSTANTS_H_
#define _AUTO_GEN_GLOBAL_CONSTANTS_H_

#define MODULE_HV 1ULL
#define MIN_UPDATE_HV 0ULL
#define NO_DOWNGRADE 1ULL
#define HANDOFF_DATA_NUM_BLOBS 0ULL
#define CRYPTO_LIB_COMPAT_VERSION 1ULL // ICP 1.0.1
#define MIN_EXPORT_VERSION 0ULL
#define MAX_EXPORT_VERSION 0ULL
#define MIN_IMPORT_VERSION 0ULL
#define MAX_IMPORT_VERSION 0ULL
#define MAX_CPUID_CONFIG 32ULL
#define MAX_CPUID_LOOKUP 80ULL
#define MAX_CPUID_LOOKUP_TDCS 80ULL
#define MAX_CPUID_LOOKUP_TDVPS 128ULL
#define MAX_CPUID_NATIVE 20ULL
#define MAX_EVENT_FILTERS 512ULL
#define MAX_GP_CTRS 8ULL
#define MAX_FIXED_CTRS 7ULL
#define MAX_RELOADABLE_FIXED_CTRS 0ULL
#define MAX_MEM_SCAN_RANGES 128ULL
#define NUM_MEM_SCAN_CONTEXTS 256ULL
#define MAX_VCPUS_PER_TD 576ULL
#define NUM_KOT_ENTRIES 2048ULL
#define XCR0_MAX_BIT 18ULL

#endif /* _AUTO_GEN_GLOBAL_CONSTANTS_H_ */
