// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "8fac3b4"
 *  Spreadsheet Format Version - '0'
 **/

#ifndef _AUTO_GEN_HANDOFF_CONSTANTS_H_
#define _AUTO_GEN_HANDOFF_CONSTANTS_H_


#include "data_structures/preserving_defs.h"

// Const values

#define MIN_UPDATE_COMPATIBILITY_HV 1ULL
#define MIN_NON_BLOCKING_EXPORT_HV 2ULL


// Static asserts

tdx_static_assert(offsetof(td_preserving_hod_t, header) == 0x0000, header);
tdx_static_assert(offsetof(td_preserving_hod_t, kot_entries) == 0x0008, kot_entries);
tdx_static_assert(offsetof(td_preserving_hod_t, wbt_entries) == 0x4008, wbt_entries);
tdx_static_assert(offsetof(td_preserving_hod_t, tdmr_table) == 0x8088, tdmr_table);
tdx_static_assert(offsetof(td_preserving_hod_t, num_of_tdmr_entries) == 0xD088, num_of_tdmr_entries);
tdx_static_assert(offsetof(td_preserving_hod_t, hkid) == 0xD08C, hkid);
tdx_static_assert(offsetof(td_preserving_hod_t, package_config_bitmap) == 0xD08E, package_config_bitmap);
tdx_static_assert(offsetof(td_preserving_hod_t, dynamic_pamt_enabled) == 0xD092, dynamic_pamt_enabled);
tdx_static_assert(offsetof(td_preserving_hod_t, td_build_count) == 0xD093, td_build_count);
tdx_static_assert(offsetof(td_preserving_hod_t, mig_interrupted_count) == 0xD095, mig_interrupted_count);
tdx_static_assert(offsetof(td_preserving_hod_t, non_blocking_export) == 0xD097, non_blocking_export);
tdx_static_assert(offsetof(td_preserving_hod_t, write_blocking_export_used) == 0xD098, write_blocking_export_used);
tdx_static_assert(offsetof(td_preserving_hod_t, round_up_to_4k_1) == 0xD099, round_up_to_4k_1);
tdx_static_assert(sizeof_field(td_preserving_hod_t, header) == 0x0008, header);
tdx_static_assert(sizeof_field(td_preserving_hod_t, kot_entries) == 0x4000, kot_entries);
tdx_static_assert(sizeof_field(td_preserving_hod_t, wbt_entries) == 0x4080, wbt_entries);
tdx_static_assert(sizeof_field(td_preserving_hod_t, tdmr_table) == 0x5000, tdmr_table);
tdx_static_assert(sizeof_field(td_preserving_hod_t, num_of_tdmr_entries) == 0x0004, num_of_tdmr_entries);
tdx_static_assert(sizeof_field(td_preserving_hod_t, hkid) == 0x0002, hkid);
tdx_static_assert(sizeof_field(td_preserving_hod_t, package_config_bitmap) == 0x0004, package_config_bitmap);
tdx_static_assert(sizeof_field(td_preserving_hod_t, dynamic_pamt_enabled) == 0x0001, dynamic_pamt_enabled);
tdx_static_assert(sizeof_field(td_preserving_hod_t, td_build_count) == 0x0002, td_build_count);
tdx_static_assert(sizeof_field(td_preserving_hod_t, mig_interrupted_count) == 0x0002, mig_interrupted_count);
tdx_static_assert(sizeof_field(td_preserving_hod_t, non_blocking_export) == 0x0001, non_blocking_export);
tdx_static_assert(sizeof_field(td_preserving_hod_t, write_blocking_export_used) == 0x0001, write_blocking_export_used);
tdx_static_assert(sizeof_field(td_preserving_hod_t, round_up_to_4k_1) == 0x0F67, round_up_to_4k_1);

#endif /* _AUTO_GEN_HANDOFF_CONSTANTS_H_ */
