// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "8fac3b4"
 *  Spreadsheet Format Version - '25'
 **/

#include "data_structures/td_control_structures.h"

tdx_static_assert(offsetof(tdr_t, management_fields.fatal) == 0x0000, fatal);
tdx_static_assert(offsetof(tdr_t, management_fields.num_tdcx) == 0x0004, num_tdcx);
tdx_static_assert(offsetof(tdr_t, management_fields.chldcnt) == 0x0008, chldcnt);
tdx_static_assert(offsetof(tdr_t, management_fields.lifecycle_state) == 0x0010, lifecycle_state);
tdx_static_assert(offsetof(tdr_t, management_fields.tdcx_pa) == 0x0018, tdcx_pa);
tdx_static_assert(offsetof(tdr_t, management_fields.td_uuid) == 0x0060, td_uuid);
tdx_static_assert(offsetof(tdr_t, key_management_fields.hkid) == 0x0100, hkid);
tdx_static_assert(offsetof(tdr_t, key_management_fields.pkg_config_bitmap) == 0x0108, pkg_config_bitmap);
tdx_static_assert(offsetof(tdr_t, td_preserving_fields.handoff_version) == 0x0140, handoff_version);
tdx_static_assert(offsetof(tdr_t, td_preserving_fields.seamdb_index) == 0x0148, seamdb_index);
tdx_static_assert(offsetof(tdcs_t, management_fields.num_vcpus) == 0x0000, num_vcpus);
tdx_static_assert(offsetof(tdcs_t, management_fields.num_assoc_vcpus) == 0x0004, num_assoc_vcpus);
tdx_static_assert(offsetof(tdcs_t, management_fields.op_state) == 0x0008, op_state);
tdx_static_assert(offsetof(tdcs_t, management_fields.num_l2_vms) == 0x0010, num_l2_vms);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.attributes) == 0x0080, attributes);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.xfam) == 0x0088, xfam);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.max_vcpus) == 0x0090, max_vcpus);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.gpaw) == 0x0094, gpaw);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.eptp) == 0x0098, eptp);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.tsc_offset) == 0x00A8, tsc_offset);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.tsc_multiplier) == 0x00B0, tsc_multiplier);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.tsc_frequency) == 0x00B8, tsc_frequency);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.xbuff_size) == 0x00DC, xbuff_size);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.notify_enables) == 0x00E0, notify_enables);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.hp_lock_timeout) == 0x00E8, hp_lock_timeout);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.vm_ctls) == 0x00F0, vm_ctls);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.config_flags) == 0x0118, config_flags);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.td_ctls) == 0x0120, td_ctls);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.virt_maxpa) == 0x0128, virt_maxpa);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.topology_enum_configured) == 0x012C, topology_enum_configured);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.ve_reduction_valid) == 0x012D, ve_reduction_valid);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.cpuid_fixed0_bitmap) == 0x0F08, cpuid_fixed0_bitmap);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.feature_paravirt_ctls) == 0x0F58, feature_paravirt_ctls);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.filtered_events_count) == 0x0F60, filtered_events_count);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.field_support_at_init) == 0x0F84, field_support_at_init);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.blocked_count) == 0x0F88, blocked_count);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.pending_blocked_count) == 0x0F90, pending_blocked_count);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.mem_count) == 0x0F98, mem_count);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.cpuid_valid) == 0x0134, cpuid_valid);
tdx_static_assert(offsetof(tdcs_t, executions_ctl2_fields.cpuid4_native_values) == 0x0F10, cpuid4_native_values);
tdx_static_assert(offsetof(tdcs_t, executions_ctl_fields.xbuff_offsets) == 0x0190, xbuff_offsets);
tdx_static_assert(offsetof(tdcs_t, epoch_tracking.epoch_and_refcount.td_epoch) == 0x0200, td_epoch);
tdx_static_assert(offsetof(tdcs_t, epoch_tracking.epoch_and_refcount.refcount) == 0x0208, refcount);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrtd) == 0x0240, mrtd);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrconfigid) == 0x0270, mrconfigid);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrowner) == 0x02A0, mrowner);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.mrownerconfig) == 0x02D0, mrownerconfig);
tdx_static_assert(offsetof(tdcs_t, measurement_fields.rtmr) == 0x0300, rtmr);
tdx_static_assert(offsetof(tdcs_t, cpuid_values) == 0x0800, cpuid_values);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_arch_capabilities) == 0x0778, virtual_ia32_arch_capabilities);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_basic) == 0x0700, virtual_ia32_vmx_basic);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_misc) == 0x0708, virtual_ia32_vmx_misc);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr0_fixed0) == 0x0710, virtual_ia32_vmx_cr0_fixed0);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr0_fixed1) == 0x0718, virtual_ia32_vmx_cr0_fixed1);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr4_fixed0) == 0x0720, virtual_ia32_vmx_cr4_fixed0);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_cr4_fixed1) == 0x0728, virtual_ia32_vmx_cr4_fixed1);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_procbased_ctls2) == 0x0730, virtual_ia32_vmx_procbased_ctls2);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_ept_vpid_cap) == 0x0738, virtual_ia32_vmx_ept_vpid_cap);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_pinbased_ctls) == 0x0740, virtual_ia32_vmx_true_pinbased_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_procbased_ctls) == 0x0748, virtual_ia32_vmx_true_procbased_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_exit_ctls) == 0x0750, virtual_ia32_vmx_true_exit_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_true_entry_ctls) == 0x0758, virtual_ia32_vmx_true_entry_ctls);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_vmfunc) == 0x0760, virtual_ia32_vmx_vmfunc);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_procbased_ctls3) == 0x0768, virtual_ia32_vmx_procbased_ctls3);
tdx_static_assert(offsetof(tdcs_t, virt_msrs.virtual_ia32_vmx_exit_ctls2) == 0x0770, virtual_ia32_vmx_exit_ctls2);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_dec_key_set) == 0x0580, mig_dec_key_set);
tdx_static_assert(offsetof(tdcs_t, migration_fields.export_count) == 0x0584, export_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.import_count) == 0x0588, import_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_epoch) == 0x058C, mig_epoch);
tdx_static_assert(offsetof(tdcs_t, migration_fields.bw_epoch) == 0x0590, bw_epoch);
tdx_static_assert(offsetof(tdcs_t, migration_fields.total_mb_count) == 0x0598, total_mb_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_dec_key) == 0x05A0, mig_dec_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_dec_working_key) == 0x05C0, mig_dec_working_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_enc_key) == 0x05E0, mig_enc_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_enc_working_key) == 0x0600, mig_enc_working_key);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_version) == 0x0620, mig_version);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_working_version) == 0x0622, mig_working_version);
tdx_static_assert(offsetof(tdcs_t, migration_fields.dirty_count) == 0x0628, dirty_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mig_count) == 0x0630, mig_count);
tdx_static_assert(offsetof(tdcs_t, migration_fields.num_migs) == 0x0638, num_migs);
tdx_static_assert(offsetof(tdcs_t, migration_fields.num_migrated_vcpus) == 0x063C, num_migrated_vcpus);
tdx_static_assert(offsetof(tdcs_t, migration_fields.num_mem_scan_ranges) == 0x0664, num_mem_scan_ranges);
tdx_static_assert(offsetof(tdcs_t, migration_fields.num_mem_scan_ranges_completed) == 0x0665, num_mem_scan_ranges_completed);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mem_scan_operation) == 0x0666, mem_scan_operation);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mem_scan_qualifier) == 0x0667, mem_scan_qualifier);
tdx_static_assert(offsetof(tdcs_t, migration_fields.mem_scan_state) == 0x0668, mem_scan_state);
tdx_static_assert(offsetof(tdcs_t, migration_fields.pre_import_uuid) == 0x0640, pre_import_uuid);
tdx_static_assert(offsetof(tdcs_t, service_td_fields.servtd_hash) == 0x0D00, servtd_hash);
tdx_static_assert(offsetof(tdcs_t, service_td_fields.servtd_num) == 0x0D30, servtd_num);
tdx_static_assert(offsetof(tdcs_t, service_td_fields.servtd_bindings_table) == 0x0D90, servtd_bindings_table);
tdx_static_assert(offsetof(tdcs_t, migsc_links) == 0x5000, migsc_links);
tdx_static_assert(offsetof(tdcs_t, x2apic_ids) == 0x1100, x2apic_ids);
tdx_static_assert(offsetof(tdcs_t, msr_bitmaps) == 0x2000, msr_bitmaps);
tdx_static_assert(offsetof(tdcs_t, sept_root) == 0x3000, sept_root);
tdx_static_assert(offsetof(tdcs_t, l2_sept_root_1) == 0x6000, l2_sept_root_1);
tdx_static_assert(offsetof(tdcs_t, l2_sept_root_2) == 0x7000, l2_sept_root_2);
tdx_static_assert(offsetof(tdcs_t, l2_sept_root_3) == 0x8000, l2_sept_root_3);
