// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "a1b03ec5" 
 *  Spreadsheet Format Version - '8'
 **/

/* 
 * CPUID configurations definitions 
 * holds all the '#define' of CPUID configurations 
 * We had to use a separate file because of a circular "include"  
 */


#ifndef _AUTO_GEN_CPUID_CONFIG_DEFINES_H_
#define _AUTO_GEN_CPUID_CONFIG_DEFINES_H_

#define MAX_NUM_CPUID_LOOKUP 73
#define MAX_NUM_CPUID_CONFIG 18

#define CPUID_CONFIG_NULL_IDX    0xFFFFFFFF

#endif /* _AUTO_GEN_CPUID_CONFIG_DEFINES_H_ */
