// Intel Proprietary
// 
// Copyright 2021 Intel Corporation All Rights Reserved.
// 
// Your use of this software is governed by the TDX Source Code LIMITED USE LICENSE.
// 
// The Materials are provided “as is,” without any express or implied warranty of any kind including warranties
// of merchantability, non-infringement, title, or fitness for a particular purpose.

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "f427aa3" 
 *  Spreadsheet Format Version - '2'
 **/

#ifndef _AUTO_GEN_CPUID_CONFIG_H_
#define _AUTO_GEN_CPUID_CONFIG_H_



#include "tdx_api_defs.h"
#include "data_structures/tdx_global_data.h"
#include "auto_gen/cpuid_configurations_defines.h"


/**
 * CPUID Lookup Table
 */
typedef struct
{
    cpuid_config_leaf_subleaf_t leaf_subleaf;

    bool_t faulting;

    cpuid_config_return_values_t verify_mask;
    cpuid_config_return_values_t verify_value;
    cpuid_config_return_values_t verify_same;

    cpuid_config_return_values_t fixed0_or_dynamic;
    cpuid_config_return_values_t fixed1;
} cpuid_lookup_t;

typedef struct
{
    cpuid_config_leaf_subleaf_t leaf_subleaf;

    cpuid_config_return_values_t config_direct;
    cpuid_config_return_values_t allow_direct;
} cpuid_configurable_t;


const cpuid_lookup_t cpuid_lookup[MAX_NUM_CPUID_LOOKUP];
const cpuid_configurable_t cpuid_configurable[MAX_NUM_CPUID_CONFIG];

const cpuid_config_return_values_t xfam_mask_0x7_0x1[XCR0_MAX_VALID_BIT + 1];
const cpuid_config_return_values_t xfam_mask_0x7_0x0[XCR0_MAX_VALID_BIT + 1];
const cpuid_config_return_values_t xfam_mask_0x1_0xffffffff[XCR0_MAX_VALID_BIT + 1];
const cpuid_config_return_values_t xfam_mask_0xd_0x0[XCR0_MAX_VALID_BIT + 1];
const cpuid_config_return_values_t xfam_mask_0xd_0x1[XCR0_MAX_VALID_BIT + 1];


#endif /* _AUTO_GEN_CPUID_CONFIG_H_ */
