// Intel Proprietary
// 
// Copyright 2021 Intel Corporation All Rights Reserved.
// 
// Your use of this software is governed by the TDX Source Code LIMITED USE LICENSE.
// 
// The Materials are provided “as is,” without any express or implied warranty of any kind including warranties
// of merchantability, non-infringement, title, or fitness for a particular purpose.

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "f427aa3" 
 *  Spreadsheet Format Version - '4'
 **/

#ifndef _AUTO_GEN_MSR_CONFIG_LOOKUP_H_
#define _AUTO_GEN_MSR_CONFIG_LOOKUP_H_



#include "tdx_api_defs.h"


#define MAX_NUM_MSR_LOOKUP 129
typedef enum
{
    MSR_BITMAP_FIXED_00,
    MSR_BITMAP_FIXED_01,
    MSR_BITMAP_FIXED_10,
    MSR_BITMAP_FIXED_1_GP_AT_EXIT,
    MSR_BITMAP_FIXED_1_OTHER,
    MSR_BITMAP_PERFMON,
    MSR_BITMAP_XFAM_CET,
    MSR_BITMAP_XFAM_PT,
    MSR_BITMAP_XFAM_ULI,
    MSR_BITMAP_XFAM_LBR,
    MSR_BITMAP_OTHER
} msr_bitmap_bit_type;

typedef struct
{
    uint32_t start_address;
    uint32_t end_address;
    msr_bitmap_bit_type bit_meaning;
} msr_lookup_t;

const msr_lookup_t msr_lookup[MAX_NUM_MSR_LOOKUP];

#endif /* _AUTO_GEN_MSR_CONFIG_LOOKUP_H_ */
