// Copyright (C) 2023 Intel Corporation                                          
//                                                                               
// Permission is hereby granted, free of charge, to any person obtaining a copy  
// of this software and associated documentation files (the "Software"),         
// to deal in the Software without restriction, including without limitation     
// the rights to use, copy, modify, merge, publish, distribute, sublicense,      
// and/or sell copies of the Software, and to permit persons to whom             
// the Software is furnished to do so, subject to the following conditions:      
//                                                                               
// The above copyright notice and this permission notice shall be included       
// in all copies or substantial portions of the Software.                        
//                                                                               
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS       
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL      
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES             
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,      
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE            
// OR OTHER DEALINGS IN THE SOFTWARE.                                            
//                                                                               
// SPDX-License-Identifier: MIT

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  based on architecture commit id "5c1d21c9" 
 *  Spreadsheet Format Version - '6'
 **/

#ifndef _AUTO_GEN_MSR_CONFIG_LOOKUP_H_
#define _AUTO_GEN_MSR_CONFIG_LOOKUP_H_



#include "tdx_api_defs.h"
#include "helpers/helpers.h"


#define MAX_NUM_MSR_LOOKUP 134

typedef struct
{
    uint32_t start_address;
    uint32_t end_address;
    msr_bitmap_bit_type rd_bit_meaning;
    msr_bitmap_action rd_action;
    msr_bitmap_bit_type wr_bit_meaning;
    msr_bitmap_action wr_action;
} msr_lookup_t;

const msr_lookup_t msr_lookup[MAX_NUM_MSR_LOOKUP];

#endif /* _AUTO_GEN_MSR_CONFIG_LOOKUP_H_ */
