// Copyright (C) 2023 Intel Corporation                                          
//                                                                               
// Permission is hereby granted, free of charge, to any person obtaining a copy  
// of this software and associated documentation files (the "Software"),         
// to deal in the Software without restriction, including without limitation     
// the rights to use, copy, modify, merge, publish, distribute, sublicense,      
// and/or sell copies of the Software, and to permit persons to whom             
// the Software is furnished to do so, subject to the following conditions:      
//                                                                               
// The above copyright notice and this permission notice shall be included       
// in all copies or substantial portions of the Software.                        
//                                                                               
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS       
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL      
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES             
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,      
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE            
// OR OTHER DEALINGS IN THE SOFTWARE.                                            
//                                                                               
// SPDX-License-Identifier: MIT

/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  Spreadsheet Format Version - '2'
 **/

#include "auto_gen/sept_state_lookup.h"


const bool_t seamcall_sept_state_lookup[MAX_SEAMCALL_LEAF][NUM_SEPT_STATES] = {
    [2] = {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [3] = {1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [5] = {0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [6] = {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [7] = {0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0 },
    [12] = {0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0 },
    [14] = {0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 },
    [15] = {0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0 },
    [16] = {0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [23] = {0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [25] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
    [29] = {0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0 },
    [30] = {0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    [39] = {0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 },
    [65] = {0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0 },
    [66] = {0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1 },
    [68] = {0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1 },
    [75] = {0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1 },
    [83] = {1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 }
};



const bool_t tdcall_sept_state_lookup[MAX_TDCALL_LEAF][NUM_SEPT_STATES] = {
    [6] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0 },
    [23] = {0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1 },
    [24] = {0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0 }
};



const sept_special_flags_t sept_special_flags_lookup[MAX_SEPT_STATE_ENC] = {
  [14] = {
    .public_state = 0,
    .live_export_allowed = 0,
    .paused_export_allowed = 0,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 1,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 0,
    .guest_accessible_leaf = 0,
    .index = 0
  },
  [12] = {
    .public_state = 5,
    .live_export_allowed = 0,
    .paused_export_allowed = 0,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 1,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 0,
    .guest_accessible_leaf = 0,
    .index = 1
  },
  [0] = {
    .public_state = 132,
    .live_export_allowed = 0,
    .paused_export_allowed = 0,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 2
  },
  [8] = {
    .public_state = 129,
    .live_export_allowed = 0,
    .paused_export_allowed = 0,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 1,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 3
  },
  [96] = {
    .public_state = 4,
    .live_export_allowed = 0,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 1,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 1,
    .import_cancel_allowed = 1,
    .mapped_or_pending = 1,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 1,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 1,
    .index = 4
  },
  [104] = {
    .public_state = 1,
    .live_export_allowed = 0,
    .paused_export_allowed = 0,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 1,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 5
  },
  [100] = {
    .public_state = 8,
    .live_export_allowed = 1,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 1,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 1,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 1,
    .index = 6
  },
  [102] = {
    .public_state = 9,
    .live_export_allowed = 1,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 1,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 1,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 1,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 1,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 0,
    .guest_accessible_leaf = 1,
    .index = 7
  },
  [99] = {
    .public_state = 11,
    .live_export_allowed = 0,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 0,
    .re_export_allowed = 1,
    .export_cancel_allowed = 1,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 1,
    .any_exported_and_dirty = 1,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 1,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 1,
    .index = 8
  },
  [103] = {
    .public_state = 12,
    .live_export_allowed = 1,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 0,
    .re_export_allowed = 1,
    .export_cancel_allowed = 1,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 1,
    .any_exported_and_dirty = 1,
    .any_exported_and_non_dirty = 0,
    .any_pending = 0,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 1,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 1,
    .index = 9
  },
  [112] = {
    .public_state = 2,
    .live_export_allowed = 0,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 1,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 1,
    .import_cancel_allowed = 1,
    .mapped_or_pending = 1,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 1,
    .any_pending_and_guest_acceptable = 1,
    .any_blocked = 0,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 10
  },
  [120] = {
    .public_state = 3,
    .live_export_allowed = 0,
    .paused_export_allowed = 0,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 1,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 1,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 11
  },
  [116] = {
    .public_state = 16,
    .live_export_allowed = 1,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 1,
    .re_export_allowed = 0,
    .export_cancel_allowed = 0,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 0,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 0,
    .any_pending = 1,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 1,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 12
  },
  [118] = {
    .public_state = 17,
    .live_export_allowed = 1,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 0,
    .re_export_allowed = 0,
    .export_cancel_allowed = 1,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 1,
    .any_exported_and_dirty = 0,
    .any_exported_and_non_dirty = 1,
    .any_pending = 1,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 1,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 0,
    .guest_accessible_leaf = 0,
    .index = 13
  },
  [115] = {
    .public_state = 19,
    .live_export_allowed = 0,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 0,
    .re_export_allowed = 1,
    .export_cancel_allowed = 1,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 1,
    .any_exported_and_dirty = 1,
    .any_exported_and_non_dirty = 0,
    .any_pending = 1,
    .any_pending_and_guest_acceptable = 1,
    .any_blocked = 0,
    .any_blockedw = 0,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 14
  },
  [119] = {
    .public_state = 20,
    .live_export_allowed = 1,
    .paused_export_allowed = 1,
    .first_time_export_allowed = 0,
    .re_export_allowed = 1,
    .export_cancel_allowed = 1,
    .first_time_import_allowed = 0,
    .re_import_allowed = 0,
    .import_cancel_allowed = 0,
    .mapped_or_pending = 0,
    .any_exported = 1,
    .any_exported_and_dirty = 1,
    .any_exported_and_non_dirty = 0,
    .any_pending = 1,
    .any_pending_and_guest_acceptable = 0,
    .any_blocked = 0,
    .any_blockedw = 1,
    .guest_fully_accessible_leaf = 0,
    .tlb_tracking_required = 1,
    .guest_accessible_leaf = 0,
    .index = 15
  }
};



const sept_special_flags_t l2_sept_special_flags_lookup[MAX_L2_SEPT_STATE_ENC] = {
  [0] = {
    .public_state = 64,
    .index = 0
  },
  [8] = {
    .public_state = 196,
    .index = 1
  },
  [1] = {
    .public_state = 193,
    .index = 2
  },
  [6] = {
    .public_state = 68,
    .index = 3
  },
  [7] = {
    .public_state = 65,
    .index = 4
  }
};



