// Copyright (C) 2023 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
// OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
/**
 *  This File is Automatically generated by the TDX xls extract tool
 *  Spreadsheet Format Version - '25'
 **/

#include "auto_gen/td_l2_vmcs_fields_lookup.h"


const md_lookup_t td_l2_vmcs_lookup[MAX_NUM_TD_L2_VMCS_LOOKUP] = {
 {
   // VPID // 0
   .field_id =  { .raw  = 0x0024000100000000 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Posted-interrupt notification vector // 1
   .field_id =  { .raw  = 0x0024000100000002 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // EPTP index // 2
   .field_id =  { .raw  = 0x0024000100000004 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // HLAT prefix size // 3
   .field_id =  { .raw  = 0x0024000100000006 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (-1ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest ES selector // 4
   .field_id =  { .raw  = 0x0024000100000800 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest CS selector // 5
   .field_id =  { .raw  = 0x0024000100000802 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest SS selector // 6
   .field_id =  { .raw  = 0x0024000100000804 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest DS selector // 7
   .field_id =  { .raw  = 0x0024000100000806 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest FS selector // 8
   .field_id =  { .raw  = 0x0024000100000808 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest GS selector // 9
   .field_id =  { .raw  = 0x002400010000080A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest LDTR selector // 10
   .field_id =  { .raw  = 0x002400010000080C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest TR selector // 11
   .field_id =  { .raw  = 0x002400010000080E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest Interrupt Status // 12
   .field_id =  { .raw  = 0x0024000100000810 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // PML Index // 13
   .field_id =  { .raw  = 0x0024000100000812 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFULL),
   .export_mask = (0ULL & 0xFFFFULL), .import_mask = (0ULL & 0xFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_NONE,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest UINV // 14
   .field_id =  { .raw  = 0x0024000100000814 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFULL),
   .export_mask = (-1ULL & 0xFFFFULL), .import_mask = (65535ULL & 0xFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // I/O-Bitmap Address n // 15
   .field_id =  { .raw  = 0x0024000300002000 },
   .num_of_fields = 2, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // MSR-Bitmap Address // 16
   .field_id =  { .raw  = 0x0024000300002004 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x5 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit MSR-store address // 17
   .field_id =  { .raw  = 0x0024000300002006 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x1 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit MSR-load address // 18
   .field_id =  { .raw  = 0x0024000300002008 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x1 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-entry MSR-load address // 19
   .field_id =  { .raw  = 0x002400030000200A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x1 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Executive-VMCS Pointer // 20
   .field_id =  { .raw  = 0x002400030000200C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x1 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // PML address // 21
   .field_id =  { .raw  = 0x002400030000200E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x9 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (18446744073709547520ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Time-Stamp Counter Offset // 22
   .field_id =  { .raw  = 0x0024000300002010 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Virtual-APIC address // 23
   .field_id =  { .raw  = 0x0024000300002012 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x6 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (18446744073709547520ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // APIC-access address // 24
   .field_id =  { .raw  = 0x0024000300002014 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x1 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Posted-interrupt descriptor address // 25
   .field_id =  { .raw  = 0x0024000300002016 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x9 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-Function Controls // 26
   .field_id =  { .raw  = 0x0024000300002018 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // EPTP // 27
   .field_id =  { .raw  = 0x002400030000201A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (128ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (18442240474082185215ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (128ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (128ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IESME,
   .special_rd_handling = false,
   .special_wr_handling = true 
 },
 {
   // EOI-exit bitmap n // 28
   .field_id =  { .raw  = 0x002400030000201C },
   .num_of_fields = 4, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // EPTP-list address // 29
   .field_id =  { .raw  = 0x0024000300002024 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VMREAD-bitmap address // 30
   .field_id =  { .raw  = 0x0024000300002026 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VMWRITE-bitmap address // 31
   .field_id =  { .raw  = 0x0024000300002028 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Virtualization-exception information address // 32
   .field_id =  { .raw  = 0x002400030000202A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x6 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // XSS-Exiting Bitmap // 33
   .field_id =  { .raw  = 0x002400030000202C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // ENCLS-Exiting Bitmap // 34
   .field_id =  { .raw  = 0x002400030000202E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Time-Stamp Counter Multiplier // 35
   .field_id =  { .raw  = 0x0024000300002032 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Tertiary Processor-Based VM-Exection Controls // 36
   .field_id =  { .raw  = 0x0024000300002034 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (14ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (14ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IESME,
   .special_rd_handling = false,
   .special_wr_handling = true 
 },
 {
   // ENCLV-Exiting Bitmap // 37
   .field_id =  { .raw  = 0x0024000300002036 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // low PASID directory address // 38
   .field_id =  { .raw  = 0x0024000300002038 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x5 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // high PASID directory address // 39
   .field_id =  { .raw  = 0x002400030000203A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x5 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Shared EPTP // 40
   .field_id =  { .raw  = 0x002400030000203C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x9 },
   .prod_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (4503599627366400ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (4503599627366400ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // PCONFIG-Exiting Bitmap // 41
   .field_id =  { .raw  = 0x002400030000203E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // HLAT pointer // 42
   .field_id =  { .raw  = 0x0024000300002040 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x6 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (4503599627366424ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (4503599627366424ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (4503599627366424ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_SPEC_CTRL mask // 43
   .field_id =  { .raw  = 0x002400030000204A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_SPEC_CTRL shadow // 44
   .field_id =  { .raw  = 0x002400030000204C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_NONE,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest-physical Address // 45
   .field_id =  { .raw  = 0x0024000300002400 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VMCS Link Pointer // 46
   .field_id =  { .raw  = 0x0024000300002800 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x5 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_DEBUGCTL // 47
   .field_id =  { .raw  = 0x0024000300002802 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (65479ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (18446744073709543423ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (65479ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (18446744073709543423ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (65479ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = true 
 },
 {
   // IA32_PAT // 48
   .field_id =  { .raw  = 0x0024000300002804 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_EFER // 49
   .field_id =  { .raw  = 0x0024000300002806 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (1281ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (1281ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_PERF_GLOBAL_CTRL // 50
   .field_id =  { .raw  = 0x0024000300002808 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // PDPTEn // 51
   .field_id =  { .raw  = 0x002400030000280A },
   .num_of_fields = 4, .num_of_elem = 1, .attributes = { .raw = 0x6 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_RTIT_CTL // 52
   .field_id =  { .raw  = 0x0024000300002814 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_LBR_CTL // 53
   .field_id =  { .raw  = 0x0024000300002816 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_GUEST_PKRS // 54
   .field_id =  { .raw  = 0x0024000300002818 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Pin-Based VM-Exection Controls // 55
   .field_id =  { .raw  = 0x0024000200004000 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Primary Processor-Based VM-Exection Controls // 56
   .field_id =  { .raw  = 0x0024000200004002 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (1771674116ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (1222220292ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (1224317444ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IESME,
   .special_rd_handling = false,
   .special_wr_handling = true 
 },
 {
   // Exception Bitmap // 57
   .field_id =  { .raw  = 0x0024000200004004 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (18446744073709289471ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (18446744073709289471ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (18446744073709289471ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Page-fault error-code mask // 58
   .field_id =  { .raw  = 0x0024000200004006 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Page-fault error-code match // 59
   .field_id =  { .raw  = 0x0024000200004008 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // CR3-Target Count // 60
   .field_id =  { .raw  = 0x002400020000400A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-Exit Controls // 61
   .field_id =  { .raw  = 0x002400020000400C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit MSR-store count // 62
   .field_id =  { .raw  = 0x002400020000400E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit MSR-load count // 63
   .field_id =  { .raw  = 0x0024000200004010 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-Entry Controls // 64
   .field_id =  { .raw  = 0x0024000200004012 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (512ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (512ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IESME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-entry MSR-load count // 65
   .field_id =  { .raw  = 0x0024000200004014 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-entry interruption information // 66
   .field_id =  { .raw  = 0x0024000200004016 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-entry exception error code // 67
   .field_id =  { .raw  = 0x0024000200004018 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-entry instruction length // 68
   .field_id =  { .raw  = 0x002400020000401A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // TPR threshold // 69
   .field_id =  { .raw  = 0x002400020000401C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Secondary Processor-Based VM-Exection Controls // 70
   .field_id =  { .raw  = 0x002400020000401E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (3221225472ULL & 0xFFFFFFFFULL), .prod_wr_mask = (3221225472ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (3222473732ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (4294967295ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (206650892ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (206651148ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IESME,
   .special_rd_handling = false,
   .special_wr_handling = true 
 },
 {
   // PLE_GAP // 71
   .field_id =  { .raw  = 0x0024000200004020 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // PLE_Window // 72
   .field_id =  { .raw  = 0x0024000200004022 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // Instruction Timeout Control // 73
   .field_id =  { .raw  = 0x0024000200004024 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFULL), .prod_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // TD HKID // 74
   .field_id =  { .raw  = 0x0024000200004026 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (-1ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-instruction error // 75
   .field_id =  { .raw  = 0x0024000200004400 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Exit reason // 76
   .field_id =  { .raw  = 0x0024000200004402 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit interruption information // 77
   .field_id =  { .raw  = 0x0024000200004404 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit interruption error code // 78
   .field_id =  { .raw  = 0x0024000200004406 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IDT-vectoring information // 79
   .field_id =  { .raw  = 0x0024000200004408 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IDT-vectoring error code // 80
   .field_id =  { .raw  = 0x002400020000440A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit instruction length // 81
   .field_id =  { .raw  = 0x002400020000440C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VM-exit instruction information // 82
   .field_id =  { .raw  = 0x002400020000440E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest ES limit // 83
   .field_id =  { .raw  = 0x0024000200004800 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest CS limit // 84
   .field_id =  { .raw  = 0x0024000200004802 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest SS limit // 85
   .field_id =  { .raw  = 0x0024000200004804 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest DS limit // 86
   .field_id =  { .raw  = 0x0024000200004806 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest FS limit // 87
   .field_id =  { .raw  = 0x0024000200004808 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest GS limit // 88
   .field_id =  { .raw  = 0x002400020000480A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest LDTR limit // 89
   .field_id =  { .raw  = 0x002400020000480C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest TR limit // 90
   .field_id =  { .raw  = 0x002400020000480E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest GDTR limit // 91
   .field_id =  { .raw  = 0x0024000200004810 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest IDTR limit // 92
   .field_id =  { .raw  = 0x0024000200004812 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest ES access rights // 93
   .field_id =  { .raw  = 0x0024000200004814 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest CS access rights // 94
   .field_id =  { .raw  = 0x0024000200004816 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest SS access rights // 95
   .field_id =  { .raw  = 0x0024000200004818 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest DS access rights // 96
   .field_id =  { .raw  = 0x002400020000481A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest FS access rights // 97
   .field_id =  { .raw  = 0x002400020000481C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest GS access rights // 98
   .field_id =  { .raw  = 0x002400020000481E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest LDTR access rights // 99
   .field_id =  { .raw  = 0x0024000200004820 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest TR access rights // 100
   .field_id =  { .raw  = 0x0024000200004822 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Interruptibility State // 101
   .field_id =  { .raw  = 0x0024000200004824 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Activity State // 102
   .field_id =  { .raw  = 0x0024000200004826 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest SMBASE // 103
   .field_id =  { .raw  = 0x0024000200004828 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_NONE,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_SYSENTER_CS // 104
   .field_id =  { .raw  = 0x002400020000482A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // VMX-Preemption Timer Value // 105
   .field_id =  { .raw  = 0x002400020000482E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFULL), .import_mask = (4294967295ULL & 0xFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // CR0 Guest/Host Mask // 106
   .field_id =  { .raw  = 0x0024000300006000 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // CR4 Guest/Host Mask // 107
   .field_id =  { .raw  = 0x0024000300006002 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // CR0 Read Shadow // 108
   .field_id =  { .raw  = 0x0024000300006004 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // CR4 Read Shadow // 109
   .field_id =  { .raw  = 0x0024000300006006 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // CR3-Target Values // 110
   .field_id =  { .raw  = 0x0024000300006008 },
   .num_of_fields = 4, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Exit qualification // 111
   .field_id =  { .raw  = 0x0024000300006400 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // I/O RCX // 112
   .field_id =  { .raw  = 0x0024000300006402 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // I/O RSI // 113
   .field_id =  { .raw  = 0x0024000300006404 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // I/O RDI // 114
   .field_id =  { .raw  = 0x0024000300006406 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // I/O RIP // 115
   .field_id =  { .raw  = 0x0024000300006408 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest-Linear Address // 116
   .field_id =  { .raw  = 0x002400030000640A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest CR0 // 117
   .field_id =  { .raw  = 0x0024000300006800 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (2147811359ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (2147811359ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (2147811391ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IESME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // Guest CR3 // 118
   .field_id =  { .raw  = 0x0024000300006802 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = true 
 },
 {
   // Guest CR4 // 119
   .field_id =  { .raw  = 0x0024000300006804 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (469704639ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (469704639ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (469704639ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_IESME,
   .special_rd_handling = true,
   .special_wr_handling = true 
 },
 {
   // Guest ES base // 120
   .field_id =  { .raw  = 0x0024000300006806 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest CS base // 121
   .field_id =  { .raw  = 0x0024000300006808 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest SS base // 122
   .field_id =  { .raw  = 0x002400030000680A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest DS base // 123
   .field_id =  { .raw  = 0x002400030000680C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest FS base // 124
   .field_id =  { .raw  = 0x002400030000680E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest GS base // 125
   .field_id =  { .raw  = 0x0024000300006810 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest LDTR base // 126
   .field_id =  { .raw  = 0x0024000300006812 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest TR base // 127
   .field_id =  { .raw  = 0x0024000300006814 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest GDTR base // 128
   .field_id =  { .raw  = 0x0024000300006816 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest IDTR base // 129
   .field_id =  { .raw  = 0x0024000300006818 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest DR7 // 130
   .field_id =  { .raw  = 0x002400030000681A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest RSP // 131
   .field_id =  { .raw  = 0x002400030000681C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest RIP // 132
   .field_id =  { .raw  = 0x002400030000681E },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Guest RFLAGS // 133
   .field_id =  { .raw  = 0x0024000300006820 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Pending Debug Exceptions // 134
   .field_id =  { .raw  = 0x0024000300006822 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_SYSENTER_ESP // 135
   .field_id =  { .raw  = 0x0024000300006824 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // IA32_SYSENTER_EIP // 136
   .field_id =  { .raw  = 0x0024000300006826 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // GUEST_IA32_S_CET // 137
   .field_id =  { .raw  = 0x0024000300006828 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // GUEST_SSP // 138
   .field_id =  { .raw  = 0x002400030000682A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // GUEST_IA32_INTERRUPT_SSP_TABLE_ADDR // 139
   .field_id =  { .raw  = 0x002400030000682C },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (-1ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (18446744073709551615ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_ME, .mig_import = MIG_ME,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Host GS Base // 140
   .field_id =  { .raw  = 0x0024000300006C08 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Host RSP // 141
   .field_id =  { .raw  = 0x0024000300006C14 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // Host RIP // 142
   .field_id =  { .raw  = 0x0024000300006C16 },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 },
 {
   // HOST_SSP // 143
   .field_id =  { .raw  = 0x0024000300006C1A },
   .num_of_fields = 1, .num_of_elem = 1, .attributes = { .raw = 0x0 },
   .prod_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .prod_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .dbg_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .dbg_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .l1_vmm_rd_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .l1_vmm_wr_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .export_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL), .import_mask = (0ULL & 0xFFFFFFFFFFFFFFFFULL),
   .mig_export = MIG_NONE, .mig_import = MIG_IES,
   .special_rd_handling = false,
   .special_wr_handling = false 
 }
};

